import type { ExtraEntry } from "./grade1";

export const GRADE3_MORE: ExtraEntry[] = [
  // ===== Toán — Lớp 3 =====
  {
    subjectId: "toan",
    grade: 3,
    order: 1,
    questions: [
      { type: "multiple_choice", content: "Số 500 gồm mấy trăm?", options: ["3", "4", "5", "6"], correctAnswer: "5", explanation: "500 = 5 trăm 0 chục 0 đơn vị." },
      { type: "multiple_choice", content: "Số nào đứng giữa 700 và 900 trong dãy số tròn trăm?", options: ["600", "800", "1000", "750"], correctAnswer: "800", explanation: "Trong dãy 700, 800, 900 thì 800 đứng giữa." },
      { type: "multiple_choice", content: "Số 620 đọc là gì?", options: ["Sáu trăm hai mươi", "Sáu hai mươi", "Sáu trăm hai", "Hai mươi sáu trăm"], correctAnswer: "Sáu trăm hai mươi", explanation: "620 đọc là 'sáu trăm hai mươi'." },
      { type: "multiple_choice", content: "Số nào bé hơn 300: 299 hay 301?", options: ["299", "301"], correctAnswer: "299", explanation: "299 < 300 < 301 nên 299 bé hơn." },
      { type: "multiple_choice", content: "Số lớn nhất có 3 chữ số là số nào?", options: ["900", "990", "999", "909"], correctAnswer: "999", explanation: "999 là số lớn nhất có 3 chữ số." },
    ],
  },
  {
    subjectId: "toan",
    grade: 3,
    order: 2,
    questions: [
      { type: "multiple_choice", content: "125 + 375 = ?", options: ["400", "500", "450", "600"], correctAnswer: "500", explanation: "125 + 375 = 500." },
      { type: "multiple_choice", content: "900 - 450 = ?", options: ["350", "400", "450", "500"], correctAnswer: "450", explanation: "900 - 450 = 450." },
      { type: "multiple_choice", content: "234 + 166 = ?", options: ["380", "390", "400", "410"], correctAnswer: "400", explanation: "234 + 166 = 400." },
      { type: "multiple_choice", content: "620 - 320 = ?", options: ["280", "300", "320", "340"], correctAnswer: "300", explanation: "620 - 320 = 300." },
      { type: "multiple_choice", content: "150 + 150 = ?", options: ["250", "300", "350", "200"], correctAnswer: "300", explanation: "150 + 150 = 300." },
    ],
  },
  {
    subjectId: "toan",
    grade: 3,
    order: 3,
    questions: [
      { type: "multiple_choice", content: "4 x 4 = ?", options: ["12", "14", "16", "18"], correctAnswer: "16", explanation: "4 x 4 = 16." },
      { type: "multiple_choice", content: "3 x 3 = ?", options: ["6", "9", "12", "15"], correctAnswer: "9", explanation: "3 x 3 = 9." },
      { type: "multiple_choice", content: "4 x 2 = ?", options: ["6", "8", "10", "12"], correctAnswer: "8", explanation: "4 x 2 = 8." },
      { type: "multiple_choice", content: "3 x 6 = ?", options: ["15", "18", "21", "24"], correctAnswer: "18", explanation: "3 x 6 = 18." },
      { type: "multiple_choice", content: "4 x 6 = ?", options: ["20", "22", "24", "26"], correctAnswer: "24", explanation: "4 x 6 = 24." },
    ],
  },
  {
    subjectId: "toan",
    grade: 3,
    order: 4,
    questions: [
      { type: "multiple_choice", content: "18 : 3 = ?", options: ["5", "6", "7", "8"], correctAnswer: "6", explanation: "18 : 3 = 6." },
      { type: "multiple_choice", content: "8 : 2 = ?", options: ["2", "3", "4", "5"], correctAnswer: "4", explanation: "8 : 2 = 4." },
      { type: "multiple_choice", content: "21 : 3 = ?", options: ["6", "7", "8", "9"], correctAnswer: "7", explanation: "21 : 3 = 7." },
      { type: "multiple_choice", content: "14 : 2 = ?", options: ["6", "7", "8", "9"], correctAnswer: "7", explanation: "14 : 2 = 7." },
      { type: "multiple_choice", content: "24 : 3 = ?", options: ["6", "7", "8", "9"], correctAnswer: "8", explanation: "24 : 3 = 8." },
    ],
  },
  {
    subjectId: "toan",
    grade: 3,
    order: 5,
    questions: [
      { type: "multiple_choice", content: "Hình chữ nhật dài 8cm, rộng 5cm. Chu vi là bao nhiêu?", options: ["13cm", "26cm", "40cm", "20cm"], correctAnswer: "26cm", explanation: "(8 + 5) x 2 = 26cm." },
      { type: "multiple_choice", content: "Hình vuông cạnh 9cm có chu vi bao nhiêu?", options: ["18cm", "27cm", "36cm", "45cm"], correctAnswer: "36cm", explanation: "9 x 4 = 36cm." },
      { type: "multiple_choice", content: "Hình chữ nhật có chu vi 20cm, chiều dài 6cm. Chiều rộng là bao nhiêu?", options: ["3cm", "4cm", "5cm", "14cm"], correctAnswer: "4cm", explanation: "Nửa chu vi = 20:2=10; rộng = 10 - 6 = 4cm." },
      { type: "multiple_choice", content: "Hình vuông có chu vi 28cm. Cạnh là bao nhiêu?", options: ["6cm", "7cm", "8cm", "9cm"], correctAnswer: "7cm", explanation: "Cạnh = 28 : 4 = 7cm." },
      { type: "multiple_choice", content: "Muốn tính chu vi hình chữ nhật, ta lấy gì?", options: ["(dài+rộng)x2", "dài x rộng", "dài - rộng", "(dài+rộng):2"], correctAnswer: "(dài+rộng)x2", explanation: "Đây là công thức tính chu vi hình chữ nhật." },
    ],
  },
  {
    subjectId: "toan",
    grade: 3,
    order: 6,
    questions: [
      { type: "multiple_choice", content: "Gấp 7 lên 2 lần được bao nhiêu?", options: ["9", "14", "21", "28"], correctAnswer: "14", explanation: "7 x 2 = 14." },
      { type: "multiple_choice", content: "Giảm 18 đi 3 lần được bao nhiêu?", options: ["3", "6", "9", "15"], correctAnswer: "6", explanation: "18 : 3 = 6." },
      { type: "multiple_choice", content: "Gấp 3 lên 6 lần được bao nhiêu?", options: ["9", "12", "18", "21"], correctAnswer: "18", explanation: "3 x 6 = 18." },
      { type: "multiple_choice", content: "Giảm 24 đi 4 lần được bao nhiêu?", options: ["4", "6", "8", "12"], correctAnswer: "6", explanation: "24 : 4 = 6." },
      { type: "multiple_choice", content: "Muốn giảm một số đi nhiều lần, ta làm phép tính gì?", options: ["Cộng", "Trừ", "Nhân", "Chia"], correctAnswer: "Chia", explanation: "Giảm đi nhiều lần nghĩa là chia." },
    ],
  },
  {
    subjectId: "toan",
    grade: 3,
    order: 7,
    questions: [
      { type: "multiple_choice", content: "5kg bằng bao nhiêu gam?", options: ["500", "5000", "50000", "50"], correctAnswer: "5000", explanation: "5kg = 5 x 1000g = 5000g." },
      { type: "multiple_choice", content: "2000g bằng bao nhiêu kg?", options: ["2", "20", "200", "0,2"], correctAnswer: "2", explanation: "2000g = 2kg." },
      { type: "multiple_choice", content: "1kg nặng hơn hay nhẹ hơn 800g?", options: ["Nặng hơn", "Nhẹ hơn", "Bằng nhau", "Không so sánh được"], correctAnswer: "Nặng hơn", explanation: "1kg = 1000g > 800g." },
      { type: "multiple_choice", content: "Túi gạo nặng 3kg, túi đường nặng 2kg. Cả hai túi nặng bao nhiêu?", options: ["4kg", "5kg", "6kg", "1kg"], correctAnswer: "5kg", explanation: "3kg + 2kg = 5kg." },
      { type: "multiple_choice", content: "Đơn vị nào lớn hơn: kg hay g?", options: ["kg", "g", "Bằng nhau", "Không so sánh được"], correctAnswer: "kg", explanation: "1kg = 1000g nên kg lớn hơn g." },
    ],
  },
  {
    subjectId: "toan",
    grade: 3,
    order: 8,
    questions: [
      { type: "multiple_choice", content: "Một năm nhuận, tháng 2 có bao nhiêu ngày?", options: ["28", "29", "30", "31"], correctAnswer: "29", explanation: "Năm nhuận, tháng 2 có 29 ngày." },
      { type: "multiple_choice", content: "Tháng 12 là tháng cuối cùng của năm, đúng hay sai?", options: ["Đúng", "Sai"], correctAnswer: "Đúng", explanation: "Một năm có 12 tháng, tháng 12 là tháng cuối cùng." },
      { type: "multiple_choice", content: "Ngày đầu tiên của tuần thường là ngày nào?", options: ["Chủ Nhật", "Thứ Hai", "Thứ Bảy", "Thứ Ba"], correctAnswer: "Thứ Hai", explanation: "Tuần thường bắt đầu từ Thứ Hai." },
      { type: "multiple_choice", content: "Tháng 6 có bao nhiêu ngày?", options: ["28", "30", "31", "29"], correctAnswer: "30", explanation: "Tháng 6 có 30 ngày." },
      { type: "multiple_choice", content: "Một năm không nhuận có bao nhiêu ngày?", options: ["360", "365", "366", "370"], correctAnswer: "365", explanation: "Một năm thường có 365 ngày." },
    ],
  },

  // ===== Tiếng Việt — Lớp 3 =====
  {
    subjectId: "tieng-viet",
    grade: 3,
    order: 1,
    questions: [
      { type: "multiple_choice", content: "Câu 'Những giọt sương long lanh như hạt ngọc.' so sánh sự vật nào với sự vật nào?", options: ["Giọt sương với hạt ngọc", "Hạt ngọc với mặt trời", "Giọt sương với mặt trăng", "Không so sánh gì"], correctAnswer: "Giọt sương với hạt ngọc", explanation: "Câu so sánh giọt sương với hạt ngọc." },
      { type: "multiple_choice", content: "Từ nào cũng có thể dùng để so sánh giống từ 'như'?", options: ["là", "và", "nhưng", "thì"], correctAnswer: "là", explanation: "Từ 'là' cũng có thể dùng trong câu so sánh, ví dụ 'Quê hương là chùm khế ngọt.'" },
      { type: "multiple_choice", content: "Câu nào KHÔNG có hình ảnh so sánh?", options: ["Bé ngoan như thiên thần.", "Bé đi học mỗi ngày.", "Nụ cười em tươi như hoa.", "Đôi mắt bé đen như hạt nhãn."], correctAnswer: "Bé đi học mỗi ngày.", explanation: "Câu này không có từ so sánh, chỉ kể sự việc." },
      { type: "multiple_choice", content: "So sánh dùng để làm gì?", options: ["Làm câu văn thêm sinh động, dễ hình dung", "Làm câu văn khó hiểu hơn", "Kết thúc câu", "Nối các câu"], correctAnswer: "Làm câu văn thêm sinh động, dễ hình dung", explanation: "So sánh giúp hình ảnh trở nên sinh động và dễ hình dung hơn." },
      { type: "multiple_choice", content: "Trong câu 'Tiếng suối trong như tiếng hát xa.', sự vật nào được so sánh với 'tiếng hát xa'?", options: ["Tiếng suối", "Con suối", "Ngọn núi", "Cơn gió"], correctAnswer: "Tiếng suối", explanation: "Câu so sánh tiếng suối với tiếng hát xa." },
    ],
  },
  {
    subjectId: "tieng-viet",
    grade: 3,
    order: 2,
    questions: [
      { type: "multiple_choice", content: "Câu 'Đàn kiến hối hả kéo nhau về tổ.' có sử dụng nhân hóa không?", options: ["Có", "Không"], correctAnswer: "Có", explanation: "'Hối hả' là từ ngữ thường dùng để tả người, dùng cho đàn kiến là nhân hóa." },
      { type: "multiple_choice", content: "Cách nhân hóa nào là gọi sự vật bằng từ xưng hô người?", options: ["Gọi 'chị' cho gió", "Chỉ tả màu sắc", "Chỉ đếm số lượng", "Chỉ nói về kích thước"], correctAnswer: "Gọi 'chị' cho gió", explanation: "Gọi sự vật bằng từ xưng hô người (chị, ông, bác...) là một cách nhân hóa." },
      { type: "multiple_choice", content: "Câu nào có sử dụng nhân hóa?", options: ["Bác trâu đang cần mẫn cày ruộng.", "Trâu là loài vật to lớn.", "Con trâu có 4 chân.", "Trâu ăn cỏ mỗi ngày."], correctAnswer: "Bác trâu đang cần mẫn cày ruộng.", explanation: "Trâu được gọi 'bác' và tả 'cần mẫn' như con người." },
      { type: "multiple_choice", content: "Nhân hóa thường được dùng nhiều trong loại văn nào?", options: ["Văn miêu tả, kể chuyện", "Văn viết đơn", "Văn viết báo cáo", "Văn viết thời khóa biểu"], correctAnswer: "Văn miêu tả, kể chuyện", explanation: "Nhân hóa thường dùng trong văn miêu tả và kể chuyện để tăng tính sinh động." },
      { type: "multiple_choice", content: "Từ nào thường dùng để nhân hóa cho cây cối?", options: ["Bác, cô, chị", "Con, cái, chiếc", "Đôi, cặp", "Chiếc, cỗ"], correctAnswer: "Bác, cô, chị", explanation: "Các từ xưng hô như bác, cô, chị thường dùng để nhân hóa." },
    ],
  },
  {
    subjectId: "tieng-viet",
    grade: 3,
    order: 3,
    questions: [
      { type: "multiple_choice", content: "Câu 'Con để cặp sách ở đâu?' là câu hỏi về gì?", options: ["Thời gian", "Địa điểm", "Nguyên nhân", "Cách thức"], correctAnswer: "Địa điểm", explanation: "'Ở đâu' hỏi về địa điểm." },
      { type: "multiple_choice", content: "Câu hỏi 'Như thế nào' dùng để hỏi về điều gì?", options: ["Cách thức, tính chất", "Thời gian", "Địa điểm", "Số lượng"], correctAnswer: "Cách thức, tính chất", explanation: "'Như thế nào' hỏi về cách thức hoặc tính chất." },
      { type: "multiple_choice", content: "Câu 'Bạn Lan nghỉ học vì sao?' mong đợi câu trả lời như thế nào?", options: ["Trả lời về thời gian", "Trả lời về địa điểm", "Trả lời về lý do", "Trả lời về cách thức"], correctAnswer: "Trả lời về lý do", explanation: "'Vì sao' cần câu trả lời giải thích lý do." },
      { type: "multiple_choice", content: "Câu hỏi 'Khi nào con đi ngủ?' thường được trả lời bằng gì?", options: ["Một địa điểm", "Một mốc thời gian", "Một lý do", "Một tên người"], correctAnswer: "Một mốc thời gian", explanation: "'Khi nào' cần trả lời bằng thời gian." },
      { type: "multiple_choice", content: "Từ để hỏi nào sau đây KHÔNG dùng để hỏi về thời gian?", options: ["Khi nào", "Bao giờ", "Lúc nào", "Ở đâu"], correctAnswer: "Ở đâu", explanation: "'Ở đâu' hỏi về địa điểm, không phải thời gian." },
    ],
  },
  {
    subjectId: "tieng-viet",
    grade: 3,
    order: 4,
    questions: [
      { type: "multiple_choice", content: "Câu 'Bố mẹ và em cùng đi công viên.' cần thêm dấu phẩy ở đâu?", options: ["Sau 'Bố'", "Sau 'mẹ'", "Không cần thêm dấu phẩy", "Sau 'công viên'"], correctAnswer: "Không cần thêm dấu phẩy", explanation: "Chỉ có 2 phần được nối bằng 'và' nên không cần dấu phẩy." },
      { type: "multiple_choice", content: "Câu 'Mùa hè em thường đi biển cùng gia đình.' cần thêm dấu phẩy ở đâu?", options: ["Sau 'Mùa hè'", "Sau 'em'", "Sau 'biển'", "Sau 'gia đình'"], correctAnswer: "Sau 'Mùa hè'", explanation: "'Mùa hè' là trạng ngữ chỉ thời gian, cần dấu phẩy ngăn cách." },
      { type: "multiple_choice", content: "Dấu phẩy có thể dùng để ngăn cách phần nào trong câu?", options: ["Trạng ngữ với phần còn lại", "Chỉ dùng ở cuối câu", "Chỉ dùng ở đầu câu", "Không dùng để ngăn cách gì"], correctAnswer: "Trạng ngữ với phần còn lại", explanation: "Dấu phẩy thường ngăn cách trạng ngữ với phần chính của câu." },
      { type: "multiple_choice", content: "Câu nào sử dụng dấu phẩy đúng?", options: ["Em thích, đọc sách.", "Em thích đọc sách, vẽ tranh và chơi đàn.", "Em, thích đọc sách.", "Em thích đọc, sách."], correctAnswer: "Em thích đọc sách, vẽ tranh và chơi đàn.", explanation: "Dấu phẩy ngăn cách đúng các từ liệt kê." },
      { type: "multiple_choice", content: "Vì sao cần dùng dấu phẩy đúng chỗ?", options: ["Để câu văn rõ nghĩa, dễ hiểu", "Để câu văn dài hơn", "Để câu văn khó đọc", "Không có tác dụng gì"], correctAnswer: "Để câu văn rõ nghĩa, dễ hiểu", explanation: "Dấu phẩy giúp câu văn rõ nghĩa và dễ đọc hơn." },
    ],
  },
  {
    subjectId: "tieng-viet",
    grade: 3,
    order: 5,
    questions: [
      { type: "multiple_choice", content: "Từ nào gợi hình ảnh gắn bó với tuổi thơ ở quê?", options: ["Cánh diều", "Máy tính", "Tòa nhà cao tầng", "Xe hơi"], correctAnswer: "Cánh diều", explanation: "'Cánh diều' là hình ảnh quen thuộc với tuổi thơ ở làng quê." },
      { type: "multiple_choice", content: "Từ nào miêu tả cảnh vật quê hương vào buổi chiều?", options: ["Cánh cò bay lả", "Đèn giao thông", "Thang máy", "Tòa nhà"], correctAnswer: "Cánh cò bay lả", explanation: "'Cánh cò bay lả' là hình ảnh quen thuộc của làng quê buổi chiều." },
      { type: "multiple_choice", content: "'Giếng nước' thường gắn với hình ảnh nào?", options: ["Làng quê xưa", "Thành phố hiện đại", "Siêu thị", "Trung tâm thương mại"], correctAnswer: "Làng quê xưa", explanation: "'Giếng nước' là hình ảnh quen thuộc của làng quê xưa." },
      { type: "multiple_choice", content: "Câu nào miêu tả tình cảm với quê hương?", options: ["Em rất yêu quê hương của mình.", "Em đi học mỗi ngày.", "Em thích ăn kem.", "Em có một cây bút mới."], correctAnswer: "Em rất yêu quê hương của mình.", explanation: "Câu này thể hiện trực tiếp tình cảm với quê hương." },
      { type: "multiple_choice", content: "Từ nào sau đây có nghĩa gần với 'quê hương'?", options: ["Xứ sở", "Siêu thị", "Nhà hàng", "Trung tâm"], correctAnswer: "Xứ sở", explanation: "'Xứ sở' có nghĩa gần với 'quê hương'." },
    ],
  },
  {
    subjectId: "tieng-viet",
    grade: 3,
    order: 6,
    questions: [
      { type: "multiple_choice", content: "Từ trái nghĩa với 'dài' là gì?", options: ["Ngắn", "Rộng", "Hẹp", "Cao"], correctAnswer: "Ngắn", explanation: "'Dài' và 'ngắn' là cặp từ trái nghĩa." },
      { type: "multiple_choice", content: "Từ trái nghĩa với 'mạnh' là gì?", options: ["Khỏe", "Yếu", "To", "Nhỏ"], correctAnswer: "Yếu", explanation: "'Mạnh' và 'yếu' là cặp từ trái nghĩa." },
      { type: "multiple_choice", content: "Từ trái nghĩa với 'sáng' là gì?", options: ["Tối", "Nóng", "Lạnh", "Ẩm"], correctAnswer: "Tối", explanation: "'Sáng' và 'tối' là cặp từ trái nghĩa." },
      { type: "multiple_choice", content: "Cặp từ nào sau đây là từ trái nghĩa?", options: ["đẹp - xinh", "to - nhỏ", "vui - hớn hở", "nhanh - mau"], correctAnswer: "to - nhỏ", explanation: "'To' và 'nhỏ' có nghĩa trái ngược nhau." },
      { type: "multiple_choice", content: "Từ trái nghĩa giúp câu văn thể hiện điều gì?", options: ["Sự đối lập, tương phản", "Sự giống nhau", "Sự lặp lại", "Không có tác dụng gì"], correctAnswer: "Sự đối lập, tương phản", explanation: "Từ trái nghĩa thể hiện sự đối lập, tương phản giữa hai sự vật, đặc điểm." },
    ],
  },
  {
    subjectId: "tieng-viet",
    grade: 3,
    order: 7,
    questions: [
      { type: "multiple_choice", content: "Câu 'Cô giáo em rất hiền.' thuộc mẫu câu nào?", options: ["Ai là gì?", "Ai làm gì?", "Ai thế nào?", "Không phải câu"], correctAnswer: "Ai thế nào?", explanation: "Câu miêu tả đặc điểm 'hiền' của cô giáo." },
      { type: "multiple_choice", content: "Câu 'Bố em là kỹ sư.' thuộc mẫu câu nào?", options: ["Ai là gì?", "Ai làm gì?", "Ai thế nào?", "Không phải câu"], correctAnswer: "Ai là gì?", explanation: "Câu giới thiệu nghề nghiệp của bố." },
      { type: "multiple_choice", content: "Câu 'Đàn cá bơi tung tăng dưới hồ.' thuộc mẫu câu nào?", options: ["Ai là gì?", "Ai làm gì?", "Ai thế nào?", "Không phải câu"], correctAnswer: "Ai làm gì?", explanation: "Câu kể hoạt động 'bơi tung tăng' của đàn cá." },
      { type: "multiple_choice", content: "Mẫu câu nào dùng để giới thiệu một người, một vật?", options: ["Ai là gì?", "Ai làm gì?", "Ai thế nào?", "Không có mẫu nào"], correctAnswer: "Ai là gì?", explanation: "Mẫu 'Ai là gì?' dùng để giới thiệu." },
      { type: "multiple_choice", content: "Mẫu câu nào dùng để miêu tả đặc điểm, tính chất?", options: ["Ai là gì?", "Ai làm gì?", "Ai thế nào?", "Không có mẫu nào"], correctAnswer: "Ai thế nào?", explanation: "Mẫu 'Ai thế nào?' dùng để miêu tả đặc điểm." },
    ],
  },
  {
    subjectId: "tieng-viet",
    grade: 3,
    order: 8,
    questions: [
      { type: "multiple_choice", content: "Vì sao Hùng bị ngã xe đạp?", options: ["Bài đọc không nói rõ", "Vì trời mưa", "Vì đường trơn", "Vì xe hỏng"], correctAnswer: "Bài đọc không nói rõ", explanation: "Bài đọc chỉ kể Hùng bị ngã xe, không nêu rõ nguyên nhân." },
      { type: "multiple_choice", content: "Hành động của Mai thể hiện đức tính gì?", options: ["Ích kỷ", "Tốt bụng, biết giúp đỡ người khác", "Lười biếng", "Nóng nảy"], correctAnswer: "Tốt bụng, biết giúp đỡ người khác", explanation: "Mai đã dừng lại giúp đỡ Hùng dù bị trễ giờ, thể hiện lòng tốt." },
      { type: "multiple_choice", content: "Việc Mai bị trễ giờ học cho thấy điều gì về bạn ấy?", options: ["Mai sẵn sàng hy sinh thời gian để giúp bạn", "Mai không quan tâm đến việc học", "Mai muốn được khen", "Mai sợ bị phạt"], correctAnswer: "Mai sẵn sàng hy sinh thời gian để giúp bạn", explanation: "Mai chấp nhận trễ giờ để giúp đỡ Hùng." },
      { type: "multiple_choice", content: "Câu chuyện thuộc chủ đề gì?", options: ["Tình bạn", "Tình yêu thiên nhiên", "Lòng dũng cảm", "Ước mơ"], correctAnswer: "Tình bạn", explanation: "Câu chuyện kể về tình bạn giữa Hùng và Mai." },
      { type: "multiple_choice", content: "Con học được điều gì từ câu chuyện của Hùng và Mai?", options: ["Nên giúp đỡ bạn bè lúc khó khăn", "Nên đi học muộn", "Không nên đi xe đạp", "Nên tránh xa bạn bè"], correctAnswer: "Nên giúp đỡ bạn bè lúc khó khăn", explanation: "Câu chuyện dạy chúng ta biết giúp đỡ bạn bè khi họ gặp khó khăn." },
    ],
  },

  // ===== Tiếng Anh — Lớp 3 =====
  {
    subjectId: "tieng-anh",
    grade: 3,
    order: 1,
    questions: [
      { type: "multiple_choice", content: "'Look' nghĩa là gì?", options: ["Nhìn", "Nghe", "Nói", "Viết"], correctAnswer: "Nhìn", explanation: "'Look' nghĩa là nhìn." },
      { type: "multiple_choice", content: "Khi cô giáo nói 'Listen!', học sinh nên làm gì?", options: ["Đứng lên", "Lắng nghe", "Ngồi xuống", "Viết bài"], correctAnswer: "Lắng nghe", explanation: "'Listen!' nghĩa là lắng nghe." },
      { type: "multiple_choice", content: "'Open' và 'close' có nghĩa trái ngược nhau, đúng không?", options: ["Đúng", "Sai"], correctAnswer: "Đúng", explanation: "'Open' (mở) và 'close' (đóng) là hai hành động ngược nhau." },
      { type: "multiple_choice", content: "Từ nào dùng khi muốn học sinh đứng dậy?", options: ["Sit down", "Stand up", "Listen", "Look"], correctAnswer: "Stand up", explanation: "'Stand up' nghĩa là đứng lên." },
      { type: "multiple_choice", content: "Đâu là câu lệnh thường dùng trong lớp học?", options: ["Stand up, please.", "I am hungry.", "It's raining.", "She is my friend."], correctAnswer: "Stand up, please.", explanation: "'Stand up, please.' là câu lệnh giáo viên thường dùng." },
    ],
  },
  {
    subjectId: "tieng-anh",
    grade: 3,
    order: 2,
    questions: [
      { type: "multiple_choice", content: "'Forty' nghĩa là số mấy?", options: ["14", "40", "44", "4"], correctAnswer: "40", explanation: "'Forty' nghĩa là số 40." },
      { type: "multiple_choice", content: "Số 90 trong tiếng Anh đọc là gì?", options: ["Nineteen", "Ninety", "Nine", "Ninth"], correctAnswer: "Ninety", explanation: "Số 90 đọc là 'ninety'." },
      { type: "multiple_choice", content: "'Seventy' nghĩa là số mấy?", options: ["17", "70", "77", "7"], correctAnswer: "70", explanation: "'Seventy' nghĩa là số 70." },
      { type: "multiple_choice", content: "Số nào lớn hơn: 'sixty' hay 'forty'?", options: ["sixty", "forty"], correctAnswer: "sixty", explanation: "'Sixty' (60) lớn hơn 'forty' (40)." },
      { type: "multiple_choice", content: "Số 100 còn có cách gọi khác là gì?", options: ["A hundred", "A thousand", "A dozen", "A half"], correctAnswer: "A hundred", explanation: "100 cũng có thể gọi là 'a hundred'." },
    ],
  },
  {
    subjectId: "tieng-anh",
    grade: 3,
    order: 3,
    questions: [
      { type: "multiple_choice", content: "'Grandmother' nghĩa là gì?", options: ["Bà", "Ông", "Cô", "Dì"], correctAnswer: "Bà", explanation: "'Grandmother' nghĩa là bà." },
      { type: "multiple_choice", content: "'Grandparents' nghĩa là gì?", options: ["Ông bà", "Cha mẹ", "Anh chị em", "Cô dì chú bác"], correctAnswer: "Ông bà", explanation: "'Grandparents' nghĩa là ông bà." },
      { type: "multiple_choice", content: "Câu 'This is my aunt.' nghĩa là gì?", options: ["Đây là cô/dì của tôi", "Đây là chú/bác của tôi", "Đây là anh họ của tôi", "Đây là bạn của tôi"], correctAnswer: "Đây là cô/dì của tôi", explanation: "'Aunt' nghĩa là cô/dì." },
      { type: "multiple_choice", content: "Từ nào chỉ mối quan hệ bạn bè?", options: ["Friend", "Cousin", "Uncle", "Aunt"], correctAnswer: "Friend", explanation: "'Friend' nghĩa là bạn bè." },
      { type: "multiple_choice", content: "'Family' nghĩa là gì?", options: ["Gia đình", "Trường học", "Bạn bè", "Hàng xóm"], correctAnswer: "Gia đình", explanation: "'Family' nghĩa là gia đình." },
    ],
  },
  {
    subjectId: "tieng-anh",
    grade: 3,
    order: 4,
    questions: [
      { type: "multiple_choice", content: "'Have breakfast' nghĩa là gì?", options: ["Ăn sáng", "Ăn trưa", "Ăn tối", "Uống nước"], correctAnswer: "Ăn sáng", explanation: "'Have breakfast' nghĩa là ăn sáng." },
      { type: "multiple_choice", content: "'Go to school' nghĩa là gì?", options: ["Đi học", "Đi ngủ", "Đi chơi", "Đi ăn"], correctAnswer: "Đi học", explanation: "'Go to school' nghĩa là đi học." },
      { type: "multiple_choice", content: "Việc nào thường làm trước tiên trong ngày?", options: ["Go to bed", "Wake up", "Have dinner", "Do homework"], correctAnswer: "Wake up", explanation: "'Wake up' (thức dậy) thường là việc đầu tiên trong ngày." },
      { type: "multiple_choice", content: "'Take a shower' nghĩa là gì?", options: ["Tắm", "Ăn cơm", "Đi ngủ", "Đánh răng"], correctAnswer: "Tắm", explanation: "'Take a shower' nghĩa là tắm." },
      { type: "multiple_choice", content: "Câu 'I go to bed at 9 pm.' nghĩa là gì?", options: ["Tôi đi ngủ lúc 9 giờ tối", "Tôi thức dậy lúc 9 giờ tối", "Tôi ăn tối lúc 9 giờ", "Tôi học bài lúc 9 giờ"], correctAnswer: "Tôi đi ngủ lúc 9 giờ tối", explanation: "'Go to bed at 9 pm' nghĩa là đi ngủ lúc 9 giờ tối." },
    ],
  },
  {
    subjectId: "tieng-anh",
    grade: 3,
    order: 5,
    questions: [
      { type: "multiple_choice", content: "'Table tennis' nghĩa là môn gì?", options: ["Bóng bàn", "Bóng rổ", "Bóng đá", "Cầu lông"], correctAnswer: "Bóng bàn", explanation: "'Table tennis' nghĩa là bóng bàn." },
      { type: "multiple_choice", content: "'I play badminton with my friend.' nghĩa là gì?", options: ["Tôi chơi cầu lông với bạn", "Tôi bơi cùng bạn", "Tôi chạy bộ cùng bạn", "Tôi đá bóng cùng bạn"], correctAnswer: "Tôi chơi cầu lông với bạn", explanation: "'Badminton' nghĩa là cầu lông." },
      { type: "multiple_choice", content: "Môn thể thao nào chơi dưới nước?", options: ["Swimming", "Football", "Basketball", "Running"], correctAnswer: "Swimming", explanation: "'Swimming' (bơi lội) là môn thể thao dưới nước." },
      { type: "multiple_choice", content: "'Volleyball' nghĩa là môn gì?", options: ["Bóng chuyền", "Bóng đá", "Bóng rổ", "Bóng bàn"], correctAnswer: "Bóng chuyền", explanation: "'Volleyball' nghĩa là bóng chuyền." },
      { type: "multiple_choice", content: "Từ nào nghĩa là 'chơi thể thao'?", options: ["Play sports", "Eat sports", "Read sports", "Watch only"], correctAnswer: "Play sports", explanation: "'Play sports' nghĩa là chơi thể thao." },
    ],
  },
  {
    subjectId: "tieng-anh",
    grade: 3,
    order: 6,
    questions: [
      { type: "multiple_choice", content: "'House' và 'home' đều có nghĩa liên quan đến gì?", options: ["Trường học", "Nhà", "Công viên", "Chợ"], correctAnswer: "Nhà", explanation: "Cả 'house' và 'home' đều liên quan đến nhà." },
      { type: "multiple_choice", content: "'Roof' nghĩa là gì?", options: ["Mái nhà", "Cửa sổ", "Cửa ra vào", "Sân"], correctAnswer: "Mái nhà", explanation: "'Roof' nghĩa là mái nhà." },
      { type: "multiple_choice", content: "'Door' nghĩa là gì?", options: ["Cửa ra vào", "Cửa sổ", "Mái nhà", "Sân"], correctAnswer: "Cửa ra vào", explanation: "'Door' nghĩa là cửa ra vào." },
      { type: "multiple_choice", content: "Phòng nào dùng để nấu ăn?", options: ["Kitchen", "Bedroom", "Bathroom", "Living room"], correctAnswer: "Kitchen", explanation: "'Kitchen' (nhà bếp) là nơi nấu ăn." },
      { type: "multiple_choice", content: "'Window' nghĩa là gì?", options: ["Cửa sổ", "Cửa ra vào", "Mái nhà", "Tường"], correctAnswer: "Cửa sổ", explanation: "'Window' nghĩa là cửa sổ." },
    ],
  },
  {
    subjectId: "tieng-anh",
    grade: 3,
    order: 7,
    questions: [
      { type: "multiple_choice", content: "'Excited' nghĩa là cảm xúc gì?", options: ["Hào hứng", "Buồn chán", "Mệt mỏi", "Sợ hãi"], correctAnswer: "Hào hứng", explanation: "'Excited' nghĩa là hào hứng, phấn khích." },
      { type: "multiple_choice", content: "'Scared' nghĩa là cảm xúc gì?", options: ["Vui vẻ", "Sợ hãi", "Tức giận", "Đói"], correctAnswer: "Sợ hãi", explanation: "'Scared' nghĩa là sợ hãi." },
      { type: "multiple_choice", content: "Từ nào diễn tả cảm giác no, trái với 'hungry'?", options: ["Full", "Tired", "Angry", "Sad"], correctAnswer: "Full", explanation: "'Full' nghĩa là no, trái nghĩa với 'hungry' (đói)." },
      { type: "multiple_choice", content: "'I am tired.' nghĩa là gì?", options: ["Tôi mệt", "Tôi vui", "Tôi buồn", "Tôi đói"], correctAnswer: "Tôi mệt", explanation: "'Tired' nghĩa là mệt." },
      { type: "multiple_choice", content: "Từ nào diễn tả cảm xúc tích cực?", options: ["Happy", "Sad", "Angry", "Scared"], correctAnswer: "Happy", explanation: "'Happy' (vui) là cảm xúc tích cực." },
    ],
  },
  {
    subjectId: "tieng-anh",
    grade: 3,
    order: 8,
    questions: [
      { type: "multiple_choice", content: "Mùa nào thường có lá vàng rơi?", options: ["Spring", "Summer", "Autumn", "Winter"], correctAnswer: "Autumn", explanation: "Mùa thu (autumn) thường có lá vàng rơi." },
      { type: "multiple_choice", content: "'Hot' thường gắn với mùa nào?", options: ["Summer", "Winter", "Spring", "Autumn"], correctAnswer: "Summer", explanation: "Mùa hè (summer) thường nóng." },
      { type: "multiple_choice", content: "'Cold' thường gắn với mùa nào?", options: ["Summer", "Winter", "Spring", "Autumn"], correctAnswer: "Winter", explanation: "Mùa đông (winter) thường lạnh." },
      { type: "multiple_choice", content: "Mùa nào hoa thường nở rộ?", options: ["Spring", "Summer", "Autumn", "Winter"], correctAnswer: "Spring", explanation: "Mùa xuân (spring) hoa thường nở rộ." },
      { type: "multiple_choice", content: "Câu 'It's cold in winter.' nghĩa là gì?", options: ["Trời lạnh vào mùa đông", "Trời nóng vào mùa hè", "Trời mưa vào mùa thu", "Trời ấm vào mùa xuân"], correctAnswer: "Trời lạnh vào mùa đông", explanation: "'Cold in winter' nghĩa là lạnh vào mùa đông." },
    ],
  },
];
