import type { ExtraEntry } from "./grade1";

export const GRADE4_MORE: ExtraEntry[] = [
  // ===== Toán — Lớp 4 =====
  {
    subjectId: "toan",
    grade: 4,
    order: 1,
    questions: [
      { type: "multiple_choice", content: "Số 7.000.000 đọc là gì?", options: ["Bảy trăm nghìn", "Bảy triệu", "Bảy chục triệu", "Bảy nghìn"], correctAnswer: "Bảy triệu", explanation: "7.000.000 đọc là bảy triệu." },
      { type: "multiple_choice", content: "Số nào có 6 chữ số?", options: ["999.999", "1.000.000", "100.000", "10.000.000"], correctAnswer: "999.999", explanation: "999.999 có 6 chữ số, còn 1.000.000 có 7 chữ số." },
      { type: "multiple_choice", content: "Trong số 4.567.123, chữ số 5 thuộc hàng nào?", options: ["Hàng triệu", "Hàng trăm nghìn", "Hàng chục nghìn", "Hàng nghìn"], correctAnswer: "Hàng trăm nghìn", explanation: "Đếm từ phải sang, chữ số 5 ở hàng trăm nghìn." },
      { type: "multiple_choice", content: "Số liền sau số 3.999.999 là số nào?", options: ["3.999.998", "4.000.000", "3.000.000", "4.999.999"], correctAnswer: "4.000.000", explanation: "3.999.999 + 1 = 4.000.000." },
      { type: "multiple_choice", content: "Số 'mười triệu' (10.000.000) có bao nhiêu chữ số?", options: ["7", "8", "9", "6"], correctAnswer: "8", explanation: "10.000.000 có 8 chữ số." },
    ],
  },
  {
    subjectId: "toan",
    grade: 4,
    order: 2,
    questions: [
      { type: "multiple_choice", content: "12 x 12 = ?", options: ["124", "134", "144", "154"], correctAnswer: "144", explanation: "12 x 12 = 144." },
      { type: "multiple_choice", content: "20 x 15 = ?", options: ["200", "250", "300", "350"], correctAnswer: "300", explanation: "20 x 15 = 300." },
      { type: "multiple_choice", content: "11 x 25 = ?", options: ["255", "265", "275", "285"], correctAnswer: "275", explanation: "11 x 25 = 275." },
      { type: "multiple_choice", content: "30 x 14 = ?", options: ["400", "410", "420", "430"], correctAnswer: "420", explanation: "30 x 14 = 420." },
      { type: "multiple_choice", content: "16 x 16 = ?", options: ["246", "256", "266", "276"], correctAnswer: "256", explanation: "16 x 16 = 256." },
    ],
  },
  {
    subjectId: "toan",
    grade: 4,
    order: 3,
    questions: [
      { type: "multiple_choice", content: "144 : 6 = ?", options: ["22", "23", "24", "25"], correctAnswer: "24", explanation: "144 : 6 = 24." },
      { type: "multiple_choice", content: "81 : 9 = ?", options: ["7", "8", "9", "10"], correctAnswer: "9", explanation: "81 : 9 = 9." },
      { type: "multiple_choice", content: "56 : 8 = ?", options: ["6", "7", "8", "9"], correctAnswer: "7", explanation: "56 : 8 = 7." },
      { type: "multiple_choice", content: "120 : 5 = ?", options: ["20", "24", "26", "30"], correctAnswer: "24", explanation: "120 : 5 = 24." },
      { type: "multiple_choice", content: "90 : 9 = ?", options: ["9", "10", "11", "12"], correctAnswer: "10", explanation: "90 : 9 = 10." },
    ],
  },
  {
    subjectId: "toan",
    grade: 4,
    order: 4,
    questions: [
      { type: "multiple_choice", content: "Phân số 7/10 nghĩa là chia thành mấy phần bằng nhau?", options: ["7", "10", "17", "3"], correctAnswer: "10", explanation: "Mẫu số 10 là số phần chia bằng nhau." },
      { type: "multiple_choice", content: "Phân số nào có tử số lớn hơn mẫu số?", options: ["3/5", "5/3", "2/4", "1/2"], correctAnswer: "5/3", explanation: "5/3 có tử số 5 lớn hơn mẫu số 3." },
      { type: "multiple_choice", content: "Một hình được chia làm 8 phần bằng nhau, tô màu 3 phần. Phân số chỉ phần tô màu là gì?", options: ["3/8", "8/3", "5/8", "3/5"], correctAnswer: "3/8", explanation: "Tô 3 trong 8 phần bằng nhau là 3/8." },
      { type: "multiple_choice", content: "Phân số 1/2 còn được gọi là gì?", options: ["Một nửa", "Một phần ba", "Một phần tư", "Toàn bộ"], correctAnswer: "Một nửa", explanation: "1/2 nghĩa là một nửa." },
      { type: "multiple_choice", content: "Phân số nào bằng 1 (toàn bộ)?", options: ["1/2", "2/2", "3/2", "1/3"], correctAnswer: "2/2", explanation: "2/2 = 1, biểu diễn toàn bộ." },
    ],
  },
  {
    subjectId: "toan",
    grade: 4,
    order: 5,
    questions: [
      { type: "multiple_choice", content: "So sánh 6/10 và 6/8 (cùng tử số)", options: ["6/10 > 6/8", "6/10 < 6/8", "6/10 = 6/8", "Không so sánh được"], correctAnswer: "6/10 < 6/8", explanation: "Cùng tử số, mẫu số nhỏ hơn thì phân số lớn hơn: 6/8 > 6/10." },
      { type: "multiple_choice", content: "Phân số nào bé nhất: 1/2, 1/3, 1/4?", options: ["1/2", "1/3", "1/4", "Bằng nhau"], correctAnswer: "1/4", explanation: "Cùng tử số 1, mẫu số càng lớn phân số càng bé." },
      { type: "multiple_choice", content: "So sánh 7/9 và 7/9", options: [">", "<", "="], correctAnswer: "=", explanation: "Hai phân số giống hệt nhau nên bằng nhau." },
      { type: "multiple_choice", content: "Phân số nào lớn hơn: 3/4 hay 3/5?", options: ["3/4", "3/5"], correctAnswer: "3/4", explanation: "Cùng tử số, mẫu số nhỏ hơn (4<5) nên 3/4 lớn hơn." },
      { type: "multiple_choice", content: "Muốn so sánh hai phân số khác mẫu số, ta thường làm gì trước?", options: ["Quy đồng mẫu số", "Cộng chúng lại", "Nhân chúng lại", "Không cần làm gì"], correctAnswer: "Quy đồng mẫu số", explanation: "Quy đồng mẫu số giúp so sánh phân số khác mẫu dễ dàng." },
    ],
  },
  {
    subjectId: "toan",
    grade: 4,
    order: 6,
    questions: [
      { type: "multiple_choice", content: "Hình thoi có mấy đường chéo?", options: ["1", "2", "3", "4"], correctAnswer: "2", explanation: "Hình thoi có 2 đường chéo." },
      { type: "multiple_choice", content: "Trong hình bình hành, hai cạnh đối diện có đặc điểm gì?", options: ["Song song và bằng nhau", "Vuông góc với nhau", "Không liên quan", "Cắt nhau"], correctAnswer: "Song song và bằng nhau", explanation: "Đây là đặc điểm của hình bình hành." },
      { type: "multiple_choice", content: "Hình vuông có phải là một trường hợp đặc biệt của hình thoi không?", options: ["Có", "Không"], correctAnswer: "Có", explanation: "Hình vuông có 4 cạnh bằng nhau nên cũng là một hình thoi đặc biệt." },
      { type: "multiple_choice", content: "Hình nào chỉ có một cặp cạnh đối diện song song?", options: ["Hình thang", "Hình bình hành", "Hình thoi", "Hình vuông"], correctAnswer: "Hình thang", explanation: "Hình thang chỉ có một cặp cạnh đối diện song song." },
      { type: "multiple_choice", content: "Hình thoi có các góc đối diện như thế nào?", options: ["Bằng nhau", "Luôn là góc vuông", "Không xác định", "Luôn khác nhau"], correctAnswer: "Bằng nhau", explanation: "Trong hình thoi, các góc đối diện bằng nhau." },
    ],
  },
  {
    subjectId: "toan",
    grade: 4,
    order: 7,
    questions: [
      { type: "multiple_choice", content: "Hình chữ nhật dài 10cm, rộng 4cm. Diện tích là bao nhiêu?", options: ["14cm²", "28cm²", "40cm²", "44cm²"], correctAnswer: "40cm²", explanation: "10 x 4 = 40cm²." },
      { type: "multiple_choice", content: "Hình vuông cạnh 8cm có diện tích bao nhiêu?", options: ["16cm²", "32cm²", "64cm²", "72cm²"], correctAnswer: "64cm²", explanation: "8 x 8 = 64cm²." },
      { type: "multiple_choice", content: "Hình chữ nhật có diện tích 24cm², chiều dài 6cm. Chiều rộng là bao nhiêu?", options: ["3cm", "4cm", "5cm", "6cm"], correctAnswer: "4cm", explanation: "Rộng = 24 : 6 = 4cm." },
      { type: "multiple_choice", content: "Đơn vị đo diện tích thường dùng là gì?", options: ["cm", "cm²", "kg", "lít"], correctAnswer: "cm²", explanation: "Diện tích đo bằng đơn vị vuông như cm²." },
      { type: "multiple_choice", content: "Hình vuông có diện tích 36cm². Cạnh là bao nhiêu?", options: ["4cm", "5cm", "6cm", "9cm"], correctAnswer: "6cm", explanation: "6 x 6 = 36 nên cạnh là 6cm." },
    ],
  },
  {
    subjectId: "toan",
    grade: 4,
    order: 8,
    questions: [
      { type: "multiple_choice", content: "Trung bình cộng của 5, 10, 15 là bao nhiêu?", options: ["5", "10", "15", "30"], correctAnswer: "10", explanation: "(5+10+15):3 = 30:3 = 10." },
      { type: "multiple_choice", content: "Trung bình cộng của 6, 8, 10, 12 là bao nhiêu?", options: ["8", "9", "10", "11"], correctAnswer: "9", explanation: "(6+8+10+12):4 = 36:4 = 9." },
      { type: "multiple_choice", content: "Nếu trung bình cộng của 2 số là 15 và một số là 10, số còn lại là bao nhiêu?", options: ["5", "10", "20", "25"], correctAnswer: "20", explanation: "Tổng 2 số = 15 x 2 = 30; số còn lại = 30 - 10 = 20." },
      { type: "multiple_choice", content: "Trung bình cộng luôn nằm trong khoảng nào so với các số đã cho?", options: ["Nhỏ hơn số bé nhất", "Lớn hơn số lớn nhất", "Giữa số bé nhất và số lớn nhất", "Không xác định"], correctAnswer: "Giữa số bé nhất và số lớn nhất", explanation: "Trung bình cộng luôn nằm giữa giá trị nhỏ nhất và lớn nhất." },
      { type: "multiple_choice", content: "Trung bình cộng của 100 và 200 là bao nhiêu?", options: ["100", "150", "200", "300"], correctAnswer: "150", explanation: "(100+200):2 = 150." },
    ],
  },

  // ===== Tiếng Việt — Lớp 4 =====
  {
    subjectId: "tieng-viet",
    grade: 4,
    order: 1,
    questions: [
      { type: "multiple_choice", content: "Từ 'bàn ghế' thuộc từ loại nào?", options: ["Danh từ", "Động từ", "Tính từ", "Không phải từ loại"], correctAnswer: "Danh từ", explanation: "'Bàn ghế' chỉ đồ vật, là danh từ." },
      { type: "multiple_choice", content: "Từ 'đọc' thuộc từ loại nào?", options: ["Danh từ", "Động từ", "Tính từ", "Không phải từ loại"], correctAnswer: "Động từ", explanation: "'Đọc' chỉ hoạt động, là động từ." },
      { type: "multiple_choice", content: "Từ 'to lớn' thuộc từ loại nào?", options: ["Danh từ", "Động từ", "Tính từ", "Không phải từ loại"], correctAnswer: "Tính từ", explanation: "'To lớn' chỉ đặc điểm, là tính từ." },
      { type: "multiple_choice", content: "Câu nào chỉ gồm toàn danh từ?", options: ["Bàn, ghế, sách, vở", "Chạy, nhảy, hát, múa", "Đẹp, xinh, cao, thấp", "Nhanh, chậm, to, nhỏ"], correctAnswer: "Bàn, ghế, sách, vở", explanation: "Đây đều là các từ chỉ đồ vật, tức danh từ." },
      { type: "multiple_choice", content: "Động từ dùng để chỉ điều gì?", options: ["Hoạt động, trạng thái", "Tên gọi sự vật", "Đặc điểm, tính chất", "Số lượng"], correctAnswer: "Hoạt động, trạng thái", explanation: "Động từ chỉ hoạt động hoặc trạng thái." },
    ],
  },
  {
    subjectId: "tieng-viet",
    grade: 4,
    order: 2,
    questions: [
      { type: "multiple_choice", content: "Câu 'Bạn có khỏe không?' là câu gì?", options: ["Câu kể", "Câu hỏi", "Câu cảm", "Câu khiến"], correctAnswer: "Câu hỏi", explanation: "Đây là câu dùng để hỏi thăm." },
      { type: "multiple_choice", content: "Câu 'Chao ôi, cảnh đẹp quá!' là câu gì?", options: ["Câu kể", "Câu hỏi", "Câu cảm", "Câu khiến"], correctAnswer: "Câu cảm", explanation: "Câu bộc lộ cảm xúc ngạc nhiên, thích thú." },
      { type: "multiple_choice", content: "Câu 'Xin hãy giúp tôi một tay!' là câu gì?", options: ["Câu kể", "Câu hỏi", "Câu cảm", "Câu khiến"], correctAnswer: "Câu khiến", explanation: "Đây là câu đề nghị, yêu cầu giúp đỡ." },
      { type: "multiple_choice", content: "Câu nào là câu kể?", options: ["Bạn tên là gì?", "Em thích đọc sách.", "Ôi, đẹp quá!", "Hãy im lặng!"], correctAnswer: "Em thích đọc sách.", explanation: "Đây là câu kể lại sự việc bình thường." },
      { type: "multiple_choice", content: "Dấu câu nào thường dùng để kết thúc câu khiến?", options: ["Dấu chấm", "Dấu chấm hỏi", "Dấu chấm than", "Dấu phẩy"], correctAnswer: "Dấu chấm than", explanation: "Câu khiến thường kết thúc bằng dấu chấm than." },
    ],
  },
  {
    subjectId: "tieng-viet",
    grade: 4,
    order: 3,
    questions: [
      { type: "multiple_choice", content: "Chủ ngữ trong câu 'Con mèo nằm sưởi nắng.' là gì?", options: ["Con mèo", "nằm", "sưởi nắng", "nằm sưởi nắng"], correctAnswer: "Con mèo", explanation: "'Con mèo' trả lời cho câu hỏi 'Con gì?'." },
      { type: "multiple_choice", content: "Vị ngữ trong câu 'Học sinh đang làm bài kiểm tra.' là gì?", options: ["Học sinh", "đang làm bài kiểm tra", "bài kiểm tra", "làm bài"], correctAnswer: "đang làm bài kiểm tra", explanation: "'Đang làm bài kiểm tra' trả lời cho câu hỏi 'làm gì?'." },
      { type: "multiple_choice", content: "Một câu đầy đủ cần có tối thiểu những thành phần nào?", options: ["Chủ ngữ và vị ngữ", "Chỉ cần chủ ngữ", "Chỉ cần vị ngữ", "Không cần thành phần nào"], correctAnswer: "Chủ ngữ và vị ngữ", explanation: "Câu đầy đủ cần có chủ ngữ và vị ngữ." },
      { type: "multiple_choice", content: "Trong câu 'Những bông hoa nở rộ trong vườn.', đâu là chủ ngữ?", options: ["Những bông hoa", "nở rộ", "trong vườn", "vườn"], correctAnswer: "Những bông hoa", explanation: "'Những bông hoa' là chủ ngữ, trả lời câu hỏi 'Cái gì?'." },
      { type: "multiple_choice", content: "Vị ngữ thường đứng ở vị trí nào trong câu?", options: ["Sau chủ ngữ", "Trước chủ ngữ", "Ở giữa câu luôn", "Không có vị trí cố định"], correctAnswer: "Sau chủ ngữ", explanation: "Vị ngữ thường đứng sau chủ ngữ trong câu." },
    ],
  },
  {
    subjectId: "tieng-viet",
    grade: 4,
    order: 4,
    questions: [
      { type: "multiple_choice", content: "Từ nào có nghĩa trái ngược với 'ước mơ'?", options: ["Tuyệt vọng", "Khát vọng", "Hoài bão", "Lý tưởng"], correctAnswer: "Tuyệt vọng", explanation: "'Tuyệt vọng' trái ngược với tinh thần mơ ước, hy vọng." },
      { type: "multiple_choice", content: "Câu nào thể hiện một ước mơ?", options: ["Em ước mơ trở thành bác sĩ.", "Em đi học mỗi ngày.", "Em có một chiếc cặp mới.", "Trời hôm nay đẹp."], correctAnswer: "Em ước mơ trở thành bác sĩ.", explanation: "Câu này trực tiếp nói về ước mơ nghề nghiệp." },
      { type: "multiple_choice", content: "Để đạt được ước mơ, con cần có thái độ như thế nào?", options: ["Chăm chỉ, kiên trì", "Lười biếng", "Bỏ cuộc sớm", "Không cần cố gắng"], correctAnswer: "Chăm chỉ, kiên trì", explanation: "Chăm chỉ và kiên trì giúp con đạt được ước mơ." },
      { type: "multiple_choice", content: "'Khát vọng' và 'ước mơ' là hai từ có quan hệ gì?", options: ["Đồng nghĩa", "Trái nghĩa", "Không liên quan", "Từ nhiều nghĩa"], correctAnswer: "Đồng nghĩa", explanation: "Hai từ này có nghĩa gần giống nhau." },
      { type: "multiple_choice", content: "Chủ đề 'ước mơ' thường gắn với điều gì trong tương lai?", options: ["Mục tiêu, dự định tốt đẹp", "Nỗi buồn quá khứ", "Sự chán nản", "Sự tức giận"], correctAnswer: "Mục tiêu, dự định tốt đẹp", explanation: "Ước mơ gắn với những mục tiêu tốt đẹp trong tương lai." },
    ],
  },
  {
    subjectId: "tieng-viet",
    grade: 4,
    order: 5,
    questions: [
      { type: "multiple_choice", content: "'Bàn ghế' là từ gì?", options: ["Từ ghép", "Từ láy", "Từ đơn", "Không xác định"], correctAnswer: "Từ ghép", explanation: "'Bàn' và 'ghế' đều có nghĩa, ghép lại thành từ ghép." },
      { type: "multiple_choice", content: "'Rung rinh' là từ gì?", options: ["Từ ghép", "Từ láy", "Từ đơn", "Không xác định"], correctAnswer: "Từ láy", explanation: "'Rung rinh' có âm lặp lại, là từ láy." },
      { type: "multiple_choice", content: "Từ láy thường được dùng để làm gì trong câu văn?", options: ["Tăng tính gợi hình, gợi cảm", "Làm câu ngắn hơn", "Kết thúc câu", "Nối các câu"], correctAnswer: "Tăng tính gợi hình, gợi cảm", explanation: "Từ láy giúp câu văn sinh động, giàu hình ảnh hơn." },
      { type: "multiple_choice", content: "'Sách vở' là từ ghép hay từ láy?", options: ["Từ ghép", "Từ láy", "Từ đơn", "Không xác định"], correctAnswer: "Từ ghép", explanation: "'Sách' và 'vở' đều có nghĩa riêng, ghép lại thành từ ghép." },
      { type: "multiple_choice", content: "Từ nào sau đây là từ láy?", options: ["Lấp lánh", "Học sinh", "Bàn ghế", "Xe đạp"], correctAnswer: "Lấp lánh", explanation: "'Lấp lánh' có âm đầu lặp lại, là từ láy." },
    ],
  },
  {
    subjectId: "tieng-viet",
    grade: 4,
    order: 6,
    questions: [
      { type: "multiple_choice", content: "Dấu ngoặc kép còn được dùng để đánh dấu gì ngoài lời nói trực tiếp?", options: ["Tên riêng đặc biệt hoặc từ ngữ được nhấn mạnh", "Chỉ số lượng", "Chỉ thời gian", "Chỉ địa điểm"], correctAnswer: "Tên riêng đặc biệt hoặc từ ngữ được nhấn mạnh", explanation: "Dấu ngoặc kép cũng dùng để nhấn mạnh từ ngữ đặc biệt." },
      { type: "multiple_choice", content: "Câu nào dùng đúng dấu hai chấm?", options: ["Bố dặn: Con nhớ học bài.", "Bố dặn Con nhớ học bài.", "Bố, dặn con nhớ học bài.", "Bố dặn con! nhớ học bài."], correctAnswer: "Bố dặn: Con nhớ học bài.", explanation: "Trước lời dặn trực tiếp cần dùng dấu hai chấm." },
      { type: "multiple_choice", content: "Dấu hai chấm có thể đứng trước phần nào của câu?", options: ["Lời giải thích hoặc liệt kê", "Chỉ đứng cuối câu", "Chỉ đứng đầu câu", "Không đứng ở đâu cả"], correctAnswer: "Lời giải thích hoặc liệt kê", explanation: "Dấu hai chấm thường đứng trước lời giải thích hoặc phần liệt kê." },
      { type: "multiple_choice", content: "Trong câu có lời nói trực tiếp, dấu ngoặc kép đặt ở đâu?", options: ["Bao quanh lời nói trực tiếp", "Ở đầu câu", "Ở cuối đoạn văn", "Không cần đặt ở đâu"], correctAnswer: "Bao quanh lời nói trực tiếp", explanation: "Dấu ngoặc kép bao quanh phần lời nói trực tiếp." },
      { type: "multiple_choice", content: "Câu 'Cô giáo khen: \"Em làm bài rất tốt.\"' dùng những dấu câu đặc biệt nào?", options: ["Chỉ dấu chấm", "Dấu hai chấm và dấu ngoặc kép", "Chỉ dấu ngoặc kép", "Không có dấu đặc biệt"], correctAnswer: "Dấu hai chấm và dấu ngoặc kép", explanation: "Câu này dùng cả dấu hai chấm và dấu ngoặc kép." },
    ],
  },
  {
    subjectId: "tieng-viet",
    grade: 4,
    order: 7,
    questions: [
      { type: "multiple_choice", content: "Câu 'Em học giỏi vì em chăm chỉ.' có mấy vế câu?", options: ["1", "2", "3", "4"], correctAnswer: "2", explanation: "Câu gồm 2 vế nối bằng từ 'vì'." },
      { type: "multiple_choice", content: "Câu nào KHÔNG phải câu ghép?", options: ["Em học bài.", "Trời mưa nên đường trơn.", "Em học giỏi vì em chăm chỉ.", "Tuy khó nhưng em vẫn cố gắng."], correctAnswer: "Em học bài.", explanation: "Đây là câu đơn, chỉ có một vế." },
      { type: "multiple_choice", content: "Trong câu ghép, các vế câu được nối với nhau bằng gì?", options: ["Từ nối hoặc dấu phẩy", "Chỉ bằng dấu chấm", "Không cần nối", "Chỉ bằng khoảng trắng"], correctAnswer: "Từ nối hoặc dấu phẩy", explanation: "Các vế câu ghép được nối bằng từ nối hoặc dấu phẩy." },
      { type: "multiple_choice", content: "Câu 'Tuy trời mưa nhưng em vẫn đi học.' dùng cặp từ nối nào?", options: ["Vì...nên", "Tuy...nhưng", "Nếu...thì", "Không những...mà còn"], correctAnswer: "Tuy...nhưng", explanation: "'Tuy...nhưng' là cặp từ nối chỉ sự tương phản." },
      { type: "multiple_choice", content: "Câu ghép giúp diễn đạt điều gì tốt hơn câu đơn?", options: ["Mối quan hệ giữa hai sự việc", "Không có tác dụng gì thêm", "Làm câu ngắn hơn", "Làm câu khó hiểu hơn"], correctAnswer: "Mối quan hệ giữa hai sự việc", explanation: "Câu ghép giúp thể hiện rõ mối quan hệ (nguyên nhân, tương phản...) giữa các sự việc." },
    ],
  },
  {
    subjectId: "tieng-viet",
    grade: 4,
    order: 8,
    questions: [
      { type: "multiple_choice", content: "Địa điểm nơi Tuấn gặp em nhỏ là ở đâu?", options: ["Bên bờ suối", "Trong rừng sâu", "Trên núi cao", "Ở sân trường"], correctAnswer: "Bên bờ suối", explanation: "Bài đọc kể Tuấn gặp em nhỏ bên bờ suối." },
      { type: "multiple_choice", content: "Điều gì khiến tình huống trong bài đọc trở nên khó khăn hơn?", options: ["Trời đã tối", "Trời nắng nóng", "Có nhiều người xung quanh", "Đường rất gần"], correctAnswer: "Trời đã tối", explanation: "Bài đọc nói dù trời đã tối, Tuấn vẫn ở lại giúp em nhỏ." },
      { type: "multiple_choice", content: "Lòng dũng cảm trong câu chuyện được thể hiện qua hành động nào?", options: ["Ở lại giúp em nhỏ dù trời tối", "Chạy về nhà trước", "Gọi bạn bè đến chơi", "Bỏ mặc em nhỏ"], correctAnswer: "Ở lại giúp em nhỏ dù trời tối", explanation: "Đây là hành động thể hiện lòng dũng cảm của Tuấn." },
      { type: "multiple_choice", content: "Qua câu chuyện, tác giả muốn ca ngợi điều gì?", options: ["Lòng dũng cảm và tốt bụng", "Sự nhút nhát", "Sự ích kỷ", "Sự lười biếng"], correctAnswer: "Lòng dũng cảm và tốt bụng", explanation: "Câu chuyện ca ngợi lòng dũng cảm, sẵn sàng giúp đỡ người khác." },
      { type: "multiple_choice", content: "Việc làm của Tuấn có ý nghĩa gì đối với em nhỏ bị lạc?", options: ["Giúp em nhỏ an toàn và được đoàn tụ với gia đình", "Không có ý nghĩa gì", "Làm em nhỏ sợ hãi hơn", "Khiến em nhỏ lạc thêm"], correctAnswer: "Giúp em nhỏ an toàn và được đoàn tụ với gia đình", explanation: "Nhờ Tuấn, em nhỏ được an toàn và tìm lại được bố mẹ." },
    ],
  },

  // ===== Tiếng Anh — Lớp 4 =====
  {
    subjectId: "tieng-anh",
    grade: 4,
    order: 1,
    questions: [
      { type: "multiple_choice", content: "'It's 9 o'clock.' nghĩa là gì?", options: ["Bây giờ là 9 giờ", "Bây giờ là 9 giờ rưỡi", "Bây giờ là 9 giờ kém 15", "Bây giờ là 9 giờ 45"], correctAnswer: "Bây giờ là 9 giờ", explanation: "'It's 9 o'clock.' nghĩa là 9 giờ đúng." },
      { type: "multiple_choice", content: "'It's 10:30.' còn có thể nói là gì?", options: ["It's half past 10.", "It's a quarter past 10.", "It's 10 o'clock.", "It's quarter to 10."], correctAnswer: "It's half past 10.", explanation: "10:30 còn được nói là 'half past 10' (10 giờ rưỡi)." },
      { type: "multiple_choice", content: "'Quarter to 5' nghĩa là mấy giờ?", options: ["4:45", "5:15", "5:45", "4:15"], correctAnswer: "4:45", explanation: "'Quarter to 5' nghĩa là 4 giờ 45 phút (còn 15 phút nữa là 5 giờ)." },
      { type: "multiple_choice", content: "Câu hỏi nào dùng để hỏi giờ hiện tại?", options: ["What time is it?", "What day is it?", "What is your name?", "How are you?"], correctAnswer: "What time is it?", explanation: "Đây là câu hỏi về giờ hiện tại." },
      { type: "multiple_choice", content: "'O'clock' chỉ dùng khi nào?", options: ["Khi giờ đúng, không có phút lẻ", "Khi có phút lẻ", "Khi hỏi ngày", "Khi hỏi tên"], correctAnswer: "Khi giờ đúng, không có phút lẻ", explanation: "'O'clock' chỉ dùng cho giờ đúng, ví dụ '7 o'clock'." },
    ],
  },
  {
    subjectId: "tieng-anh",
    grade: 4,
    order: 2,
    questions: [
      { type: "multiple_choice", content: "'Playing football' nghĩa là gì?", options: ["Chơi bóng đá", "Đọc sách", "Vẽ tranh", "Xem tivi"], correctAnswer: "Chơi bóng đá", explanation: "'Playing football' nghĩa là chơi bóng đá." },
      { type: "multiple_choice", content: "'Singing' nghĩa là gì?", options: ["Hát", "Nhảy múa", "Vẽ tranh", "Đọc sách"], correctAnswer: "Hát", explanation: "'Singing' nghĩa là hát." },
      { type: "multiple_choice", content: "'What do you do in your free time?' hỏi về điều gì?", options: ["Hoạt động lúc rảnh rỗi", "Nơi ở", "Món ăn yêu thích", "Ngày sinh"], correctAnswer: "Hoạt động lúc rảnh rỗi", explanation: "Câu hỏi này hỏi về sở thích lúc rảnh rỗi." },
      { type: "multiple_choice", content: "'Dancing' nghĩa là gì?", options: ["Nhảy múa", "Ca hát", "Vẽ tranh", "Chơi game"], correctAnswer: "Nhảy múa", explanation: "'Dancing' nghĩa là nhảy múa." },
      { type: "multiple_choice", content: "Hoạt động nào phù hợp khi ở trong nhà lúc trời mưa?", options: ["Reading a book", "Swimming in the sea", "Playing football outside", "Riding a bike outside"], correctAnswer: "Reading a book", explanation: "Đọc sách là hoạt động phù hợp khi ở trong nhà lúc trời mưa." },
    ],
  },
  {
    subjectId: "tieng-anh",
    grade: 4,
    order: 3,
    questions: [
      { type: "multiple_choice", content: "'Nurse' nghĩa là nghề gì?", options: ["Y tá", "Bác sĩ", "Giáo viên", "Ca sĩ"], correctAnswer: "Y tá", explanation: "'Nurse' nghĩa là y tá." },
      { type: "multiple_choice", content: "'Police officer' nghĩa là nghề gì?", options: ["Cảnh sát", "Bác sĩ", "Nông dân", "Đầu bếp"], correctAnswer: "Cảnh sát", explanation: "'Police officer' nghĩa là cảnh sát." },
      { type: "multiple_choice", content: "'Cook' nghĩa là nghề gì?", options: ["Đầu bếp", "Ca sĩ", "Kỹ sư", "Tài xế"], correctAnswer: "Đầu bếp", explanation: "'Cook' nghĩa là đầu bếp." },
      { type: "multiple_choice", content: "Câu 'What do you want to be in the future?' hỏi về điều gì?", options: ["Nghề nghiệp tương lai", "Món ăn yêu thích", "Ngày sinh nhật", "Nơi sinh sống"], correctAnswer: "Nghề nghiệp tương lai", explanation: "Câu hỏi này hỏi về ước mơ nghề nghiệp." },
      { type: "multiple_choice", content: "'My father is a driver.' nghĩa là gì?", options: ["Bố tôi là tài xế", "Bố tôi là bác sĩ", "Bố tôi là giáo viên", "Bố tôi là kỹ sư"], correctAnswer: "Bố tôi là tài xế", explanation: "'Driver' nghĩa là tài xế." },
    ],
  },
  {
    subjectId: "tieng-anh",
    grade: 4,
    order: 4,
    questions: [
      { type: "multiple_choice", content: "'In the box' nghĩa là gì?", options: ["Trong hộp", "Trên hộp", "Dưới hộp", "Bên cạnh hộp"], correctAnswer: "Trong hộp", explanation: "'In the box' nghĩa là trong hộp." },
      { type: "multiple_choice", content: "'The cat is under the bed.' nghĩa là gì?", options: ["Con mèo ở dưới giường", "Con mèo ở trên giường", "Con mèo ở cạnh giường", "Con mèo ở trong giường"], correctAnswer: "Con mèo ở dưới giường", explanation: "'Under the bed' nghĩa là dưới giường." },
      { type: "multiple_choice", content: "Giới từ nào chỉ vị trí 'ở trên'?", options: ["On", "In", "Under", "Behind"], correctAnswer: "On", explanation: "'On' nghĩa là ở trên." },
      { type: "multiple_choice", content: "'The ball is next to the chair.' nghĩa là gì?", options: ["Quả bóng ở bên cạnh ghế", "Quả bóng ở trên ghế", "Quả bóng ở dưới ghế", "Quả bóng ở sau ghế"], correctAnswer: "Quả bóng ở bên cạnh ghế", explanation: "'Next to' nghĩa là bên cạnh." },
      { type: "multiple_choice", content: "Giới từ nào chỉ vị trí 'phía sau'?", options: ["Behind", "In front of", "On", "Under"], correctAnswer: "Behind", explanation: "'Behind' nghĩa là phía sau." },
    ],
  },
  {
    subjectId: "tieng-anh",
    grade: 4,
    order: 5,
    questions: [
      { type: "multiple_choice", content: "'Bear' nghĩa là con gì?", options: ["Con gấu", "Con hổ", "Con voi", "Con khỉ"], correctAnswer: "Con gấu", explanation: "'Bear' nghĩa là con gấu." },
      { type: "multiple_choice", content: "'Crocodile' nghĩa là con gì?", options: ["Con cá sấu", "Con rắn", "Con voi", "Con hổ"], correctAnswer: "Con cá sấu", explanation: "'Crocodile' nghĩa là con cá sấu." },
      { type: "multiple_choice", content: "Con vật nào có cổ dài nhất trong các loài ở sở thú?", options: ["Giraffe", "Lion", "Monkey", "Zebra"], correctAnswer: "Giraffe", explanation: "Hươu cao cổ (giraffe) có cổ dài nhất." },
      { type: "multiple_choice", content: "'Wild animals' nghĩa là gì?", options: ["Động vật hoang dã", "Động vật nuôi trong nhà", "Động vật biển", "Động vật nhỏ"], correctAnswer: "Động vật hoang dã", explanation: "'Wild animals' nghĩa là động vật hoang dã." },
      { type: "multiple_choice", content: "Con vật nào được gọi là 'vua của rừng xanh'?", options: ["Lion", "Monkey", "Zebra", "Elephant"], correctAnswer: "Lion", explanation: "Sư tử (lion) thường được gọi là vua của rừng xanh." },
    ],
  },
  {
    subjectId: "tieng-anh",
    grade: 4,
    order: 6,
    questions: [
      { type: "multiple_choice", content: "'Motorbike' nghĩa là gì?", options: ["Xe máy", "Xe đạp", "Ô tô", "Máy bay"], correctAnswer: "Xe máy", explanation: "'Motorbike' nghĩa là xe máy." },
      { type: "multiple_choice", content: "'By bus' nghĩa là gì?", options: ["Bằng xe buýt", "Bằng xe đạp", "Bằng tàu hỏa", "Bằng máy bay"], correctAnswer: "Bằng xe buýt", explanation: "'By bus' nghĩa là bằng xe buýt (phương tiện di chuyển)." },
      { type: "multiple_choice", content: "Phương tiện nào bay trên trời?", options: ["Plane", "Boat", "Bike", "Train"], correctAnswer: "Plane", explanation: "Máy bay (plane) bay trên trời." },
      { type: "multiple_choice", content: "Phương tiện nào di chuyển trên đường ray?", options: ["Train", "Car", "Boat", "Bike"], correctAnswer: "Train", explanation: "Tàu hỏa (train) di chuyển trên đường ray." },
      { type: "multiple_choice", content: "'How do you go to school?' hỏi về điều gì?", options: ["Phương tiện đến trường", "Thời gian đến trường", "Địa điểm trường học", "Tên trường học"], correctAnswer: "Phương tiện đến trường", explanation: "Câu hỏi này hỏi về phương tiện di chuyển đến trường." },
    ],
  },
  {
    subjectId: "tieng-anh",
    grade: 4,
    order: 7,
    questions: [
      { type: "multiple_choice", content: "'Expensive' nghĩa là gì?", options: ["Đắt", "Rẻ", "Đẹp", "Xấu"], correctAnswer: "Đắt", explanation: "'Expensive' nghĩa là đắt." },
      { type: "multiple_choice", content: "'Cheap' nghĩa là gì?", options: ["Rẻ", "Đắt", "Mới", "Cũ"], correctAnswer: "Rẻ", explanation: "'Cheap' nghĩa là rẻ." },
      { type: "multiple_choice", content: "'Hat' nghĩa là gì?", options: ["Mũ", "Giày", "Áo", "Quần"], correctAnswer: "Mũ", explanation: "'Hat' nghĩa là mũ." },
      { type: "multiple_choice", content: "Câu 'It's 50,000 dong.' trả lời cho câu hỏi nào?", options: ["How much is it?", "What color is it?", "Where is it?", "When is it?"], correctAnswer: "How much is it?", explanation: "Đây là câu trả lời về giá cả." },
      { type: "multiple_choice", content: "'Buy' nghĩa là gì?", options: ["Mua", "Bán", "Cho", "Mượn"], correctAnswer: "Mua", explanation: "'Buy' nghĩa là mua." },
    ],
  },
  {
    subjectId: "tieng-anh",
    grade: 4,
    order: 8,
    questions: [
      { type: "multiple_choice", content: "'Canteen' nghĩa là gì?", options: ["Căng tin", "Thư viện", "Phòng học", "Sân chơi"], correctAnswer: "Căng tin", explanation: "'Canteen' nghĩa là căng tin." },
      { type: "multiple_choice", content: "'Teacher's room' nghĩa là gì?", options: ["Phòng giáo viên", "Phòng hiệu trưởng", "Phòng thư viện", "Phòng y tế"], correctAnswer: "Phòng giáo viên", explanation: "'Teacher's room' nghĩa là phòng giáo viên." },
      { type: "multiple_choice", content: "'I study English at school.' nghĩa là gì?", options: ["Tôi học Tiếng Anh ở trường", "Tôi học Toán ở trường", "Tôi chơi thể thao ở trường", "Tôi ăn trưa ở trường"], correctAnswer: "Tôi học Tiếng Anh ở trường", explanation: "Câu này nói về việc học Tiếng Anh ở trường." },
      { type: "multiple_choice", content: "'Librarian' nghĩa là gì?", options: ["Thủ thư", "Hiệu trưởng", "Giáo viên", "Học sinh"], correctAnswer: "Thủ thư", explanation: "'Librarian' nghĩa là thủ thư (người quản lý thư viện)." },
      { type: "multiple_choice", content: "Nơi nào trong trường dùng để mượn sách?", options: ["Library", "Playground", "Canteen", "Classroom"], correctAnswer: "Library", explanation: "Thư viện (library) là nơi mượn sách." },
    ],
  },
];
