import type { ExtraEntry } from "./grade1";

export const GRADE5_MORE: ExtraEntry[] = [
  // ===== Toán — Lớp 5 =====
  {
    subjectId: "toan",
    grade: 5,
    order: 1,
    questions: [
      { type: "multiple_choice", content: "Rút gọn phân số 10/15 được kết quả nào?", options: ["1/2", "2/3", "3/5", "1/3"], correctAnswer: "2/3", explanation: "Chia cả tử và mẫu cho 5: 10/15 = 2/3." },
      { type: "multiple_choice", content: "Quy đồng mẫu số hai phân số 1/4 và 1/6, mẫu số chung nhỏ nhất là bao nhiêu?", options: ["10", "12", "24", "6"], correctAnswer: "12", explanation: "Mẫu số chung nhỏ nhất của 4 và 6 là 12." },
      { type: "multiple_choice", content: "Phân số 12/16 rút gọn được kết quả nào?", options: ["3/4", "4/3", "6/8", "2/3"], correctAnswer: "3/4", explanation: "Chia cả tử và mẫu cho 4: 12/16 = 3/4." },
      { type: "multiple_choice", content: "Muốn rút gọn phân số, ta chia tử số và mẫu số cho gì?", options: ["Một số tự nhiên khác 0", "Số 0", "Một số âm", "Số 1"], correctAnswer: "Một số tự nhiên khác 0", explanation: "Ta chia cả tử và mẫu cho cùng một số tự nhiên khác 0 (ước chung)." },
      { type: "multiple_choice", content: "Phân số 5/10 sau khi rút gọn tối giản là gì?", options: ["1/2", "2/5", "5/10", "1/5"], correctAnswer: "1/2", explanation: "5/10 rút gọn (chia cho 5) được 1/2." },
    ],
  },
  {
    subjectId: "toan",
    grade: 5,
    order: 2,
    questions: [
      { type: "multiple_choice", content: "1/4 + 1/2 = ?", options: ["2/6", "3/4", "1/6", "2/4"], correctAnswer: "3/4", explanation: "Quy đồng: 1/4 + 2/4 = 3/4." },
      { type: "multiple_choice", content: "7/8 - 1/4 = ?", options: ["5/8", "6/8", "3/4", "1/2"], correctAnswer: "5/8", explanation: "Quy đồng: 7/8 - 2/8 = 5/8." },
      { type: "multiple_choice", content: "2/3 + 2/3 = ?", options: ["4/3", "4/6", "2/3", "1"], correctAnswer: "4/3", explanation: "2/3 + 2/3 = 4/3." },
      { type: "multiple_choice", content: "1 - 1/4 = ?", options: ["1/4", "3/4", "1/2", "0"], correctAnswer: "3/4", explanation: "1 = 4/4; 4/4 - 1/4 = 3/4." },
      { type: "multiple_choice", content: "3/10 + 4/10 = ?", options: ["7/10", "7/20", "1/10", "12/10"], correctAnswer: "7/10", explanation: "Cùng mẫu số: 3/10 + 4/10 = 7/10." },
    ],
  },
  {
    subjectId: "toan",
    grade: 5,
    order: 3,
    questions: [
      { type: "multiple_choice", content: "3/5 x 1/2 = ?", options: ["3/10", "4/7", "3/7", "4/10"], correctAnswer: "3/10", explanation: "(3x1)/(5x2) = 3/10." },
      { type: "multiple_choice", content: "1/3 : 1/6 = ?", options: ["1/2", "2", "3", "6"], correctAnswer: "2", explanation: "1/3 : 1/6 = 1/3 x 6/1 = 6/3 = 2." },
      { type: "multiple_choice", content: "2/5 x 5/2 = ?", options: ["1", "10/10", "4/25", "2/2"], correctAnswer: "1", explanation: "(2x5)/(5x2) = 10/10 = 1." },
      { type: "multiple_choice", content: "Muốn chia hai phân số, ta nhân phân số thứ nhất với gì?", options: ["Phân số đảo ngược của phân số thứ hai", "Phân số thứ hai", "Số 1", "Số 0"], correctAnswer: "Phân số đảo ngược của phân số thứ hai", explanation: "Chia phân số bằng cách nhân với phân số đảo ngược." },
      { type: "multiple_choice", content: "1/2 x 1/2 = ?", options: ["1/4", "2/4", "1/2", "2/2"], correctAnswer: "1/4", explanation: "(1x1)/(2x2) = 1/4." },
    ],
  },
  {
    subjectId: "toan",
    grade: 5,
    order: 4,
    questions: [
      { type: "multiple_choice", content: "Số 25,4 có phần thập phân là chữ số nào?", options: ["2", "5", "4", "0"], correctAnswer: "4", explanation: "Chữ số 4 đứng sau dấu phẩy là phần thập phân." },
      { type: "multiple_choice", content: "Số nào là số thập phân?", options: ["12", "7,5", "100", "0"], correctAnswer: "7,5", explanation: "7,5 có dấu phẩy ngăn cách phần nguyên và phần thập phân, là số thập phân." },
      { type: "multiple_choice", content: "Số 4,25 đọc là gì?", options: ["Bốn phẩy hai mươi lăm", "Bốn trăm hai mươi lăm", "Bốn phẩy hai năm", "Hai mươi lăm phẩy bốn"], correctAnswer: "Bốn phẩy hai mươi lăm", explanation: "4,25 đọc là 'bốn phẩy hai mươi lăm'." },
      { type: "multiple_choice", content: "Số 0,1 và số 0,10 có bằng nhau không?", options: ["Có", "Không"], correctAnswer: "Có", explanation: "0,1 = 0,10 vì thêm số 0 ở cuối phần thập phân không làm thay đổi giá trị." },
      { type: "multiple_choice", content: "Số thập phân nào lớn hơn: 3,4 hay 3,25?", options: ["3,4", "3,25", "Bằng nhau", "Không so sánh được"], correctAnswer: "3,4", explanation: "So sánh hàng phần mười: 4 > 2 nên 3,4 > 3,25." },
    ],
  },
  {
    subjectId: "toan",
    grade: 5,
    order: 5,
    questions: [
      { type: "multiple_choice", content: "12,5 + 3,7 = ?", options: ["15,2", "16,2", "15,7", "16,7"], correctAnswer: "16,2", explanation: "12,5 + 3,7 = 16,2." },
      { type: "multiple_choice", content: "20,0 - 8,5 = ?", options: ["11,5", "12,5", "11,0", "12,0"], correctAnswer: "11,5", explanation: "20,0 - 8,5 = 11,5." },
      { type: "multiple_choice", content: "6,25 + 1,75 = ?", options: ["7,0", "8,0", "7,5", "8,5"], correctAnswer: "8,0", explanation: "6,25 + 1,75 = 8,0." },
      { type: "multiple_choice", content: "15,6 - 5,6 = ?", options: ["9,0", "10,0", "11,0", "10,6"], correctAnswer: "10,0", explanation: "15,6 - 5,6 = 10,0." },
      { type: "multiple_choice", content: "1,1 + 1,1 + 1,1 = ?", options: ["2,2", "3,3", "3,0", "2,3"], correctAnswer: "3,3", explanation: "1,1 + 1,1 + 1,1 = 3,3." },
    ],
  },
  {
    subjectId: "toan",
    grade: 5,
    order: 6,
    questions: [
      { type: "multiple_choice", content: "5,5 x 2 = ?", options: ["10,0", "11,0", "10,5", "11,5"], correctAnswer: "11,0", explanation: "5,5 x 2 = 11,0." },
      { type: "multiple_choice", content: "8,4 : 4 = ?", options: ["2,0", "2,1", "2,2", "2,4"], correctAnswer: "2,1", explanation: "8,4 : 4 = 2,1." },
      { type: "multiple_choice", content: "0,5 x 6 = ?", options: ["2,5", "3,0", "3,5", "4,0"], correctAnswer: "3,0", explanation: "0,5 x 6 = 3,0." },
      { type: "multiple_choice", content: "12,6 : 3 = ?", options: ["4,0", "4,2", "4,4", "4,6"], correctAnswer: "4,2", explanation: "12,6 : 3 = 4,2." },
      { type: "multiple_choice", content: "2,2 x 5 = ?", options: ["10,0", "11,0", "10,5", "11,5"], correctAnswer: "11,0", explanation: "2,2 x 5 = 11,0." },
    ],
  },
  {
    subjectId: "toan",
    grade: 5,
    order: 7,
    questions: [
      { type: "multiple_choice", content: "Tam giác đáy 12cm, chiều cao 5cm. Diện tích là bao nhiêu?", options: ["17cm²", "30cm²", "60cm²", "34cm²"], correctAnswer: "30cm²", explanation: "(12 x 5) : 2 = 30cm²." },
      { type: "multiple_choice", content: "Hình thang có đáy lớn 10cm, đáy bé 6cm, chiều cao 4cm. Diện tích là bao nhiêu?", options: ["16cm²", "32cm²", "40cm²", "24cm²"], correctAnswer: "32cm²", explanation: "(10 + 6) x 4 : 2 = 32cm²." },
      { type: "multiple_choice", content: "Muốn tính diện tích hình thang, ta lấy tổng hai đáy nhân với chiều cao rồi làm gì?", options: ["Nhân 2", "Chia 2", "Cộng 2", "Trừ 2"], correctAnswer: "Chia 2", explanation: "Diện tích hình thang = (đáy lớn + đáy bé) x chiều cao : 2." },
      { type: "multiple_choice", content: "Tam giác có diện tích 24cm², chiều cao 6cm. Đáy là bao nhiêu?", options: ["4cm", "6cm", "8cm", "12cm"], correctAnswer: "8cm", explanation: "Đáy = (24 x 2) : 6 = 8cm." },
      { type: "multiple_choice", content: "Hình thang có hai đáy bằng nhau thì trở thành hình gì?", options: ["Hình bình hành", "Hình tam giác", "Hình tròn", "Hình thoi"], correctAnswer: "Hình bình hành", explanation: "Khi hai đáy bằng nhau, hình thang trở thành hình bình hành." },
    ],
  },
  {
    subjectId: "toan",
    grade: 5,
    order: 8,
    questions: [
      { type: "multiple_choice", content: "Hình hộp chữ nhật dài 6cm, rộng 4cm, cao 2cm. Thể tích là bao nhiêu?", options: ["12cm³", "24cm³", "48cm³", "36cm³"], correctAnswer: "48cm³", explanation: "6 x 4 x 2 = 48cm³." },
      { type: "multiple_choice", content: "Hình lập phương cạnh 4cm có thể tích bao nhiêu?", options: ["16cm³", "48cm³", "64cm³", "12cm³"], correctAnswer: "64cm³", explanation: "4 x 4 x 4 = 64cm³." },
      { type: "multiple_choice", content: "Thể tích hình hộp chữ nhật bằng công thức nào?", options: ["dài x rộng x cao", "dài + rộng + cao", "(dài+rộng)x cao", "dài x rộng"], correctAnswer: "dài x rộng x cao", explanation: "Đây là công thức tính thể tích hình hộp chữ nhật." },
      { type: "multiple_choice", content: "Hình lập phương có thể tích 125cm³. Cạnh là bao nhiêu?", options: ["4cm", "5cm", "6cm", "25cm"], correctAnswer: "5cm", explanation: "5 x 5 x 5 = 125cm³ nên cạnh là 5cm." },
      { type: "multiple_choice", content: "Đơn vị đo thể tích thường dùng là gì?", options: ["cm", "cm²", "cm³", "kg"], correctAnswer: "cm³", explanation: "Thể tích đo bằng đơn vị khối như cm³." },
    ],
  },

  // ===== Tiếng Việt — Lớp 5 =====
  {
    subjectId: "tieng-viet",
    grade: 5,
    order: 1,
    questions: [
      { type: "multiple_choice", content: "Từ nào đồng nghĩa với 'nhanh nhẹn'?", options: ["Lanh lợi", "Chậm chạp", "Lười biếng", "Vụng về"], correctAnswer: "Lanh lợi", explanation: "'Lanh lợi' có nghĩa gần giống 'nhanh nhẹn'." },
      { type: "multiple_choice", content: "Từ nào đồng nghĩa với 'yên tĩnh'?", options: ["Ồn ào", "Tĩnh lặng", "Náo nhiệt", "Sôi động"], correctAnswer: "Tĩnh lặng", explanation: "'Tĩnh lặng' có nghĩa gần giống 'yên tĩnh'." },
      { type: "multiple_choice", content: "Từ đồng nghĩa giúp ích gì khi viết văn?", options: ["Tránh lặp từ, làm câu văn phong phú", "Làm câu văn khó hiểu", "Làm câu văn ngắn hơn", "Không có tác dụng gì"], correctAnswer: "Tránh lặp từ, làm câu văn phong phú", explanation: "Từ đồng nghĩa giúp tránh lặp từ và làm câu văn đa dạng hơn." },
      { type: "multiple_choice", content: "Cặp từ nào là từ đồng nghĩa?", options: ["To lớn - khổng lồ", "To lớn - nhỏ bé", "Vui vẻ - buồn bã", "Nhanh - chậm"], correctAnswer: "To lớn - khổng lồ", explanation: "'To lớn' và 'khổng lồ' có nghĩa gần giống nhau." },
      { type: "multiple_choice", content: "Từ nào đồng nghĩa với 'giỏi'?", options: ["Xuất sắc", "Kém", "Tệ", "Dở"], correctAnswer: "Xuất sắc", explanation: "'Xuất sắc' có nghĩa gần giống 'giỏi'." },
    ],
  },
  {
    subjectId: "tieng-viet",
    grade: 5,
    order: 2,
    questions: [
      { type: "multiple_choice", content: "Từ 'mũi' trong 'mũi người' là nghĩa gì?", options: ["Nghĩa gốc", "Nghĩa chuyển", "Không có nghĩa", "Từ đồng âm"], correctAnswer: "Nghĩa gốc", explanation: "'Mũi người' là nghĩa gốc, chỉ bộ phận cơ thể." },
      { type: "multiple_choice", content: "Từ 'mũi' trong 'mũi thuyền' là nghĩa gì?", options: ["Nghĩa gốc", "Nghĩa chuyển", "Không xác định", "Từ trái nghĩa"], correctAnswer: "Nghĩa chuyển", explanation: "'Mũi thuyền' dùng nghĩa chuyển, chỉ phần đầu của thuyền." },
      { type: "multiple_choice", content: "Từ nhiều nghĩa khác với từ đồng âm ở điểm nào?", options: ["Các nghĩa của từ nhiều nghĩa có liên quan với nhau", "Từ nhiều nghĩa chỉ có một nghĩa", "Từ đồng âm luôn liên quan về nghĩa", "Không có sự khác biệt nào"], correctAnswer: "Các nghĩa của từ nhiều nghĩa có liên quan với nhau", explanation: "Từ nhiều nghĩa có các nghĩa liên quan nhau, khác với từ đồng âm." },
      { type: "multiple_choice", content: "Từ 'tay' trong 'tay ghế' là nghĩa gì?", options: ["Nghĩa gốc", "Nghĩa chuyển", "Không xác định", "Từ trái nghĩa"], correctAnswer: "Nghĩa chuyển", explanation: "'Tay ghế' dùng nghĩa chuyển từ 'tay' (bộ phận cơ thể)." },
      { type: "multiple_choice", content: "Nghĩa gốc của một từ là gì?", options: ["Nghĩa xuất hiện đầu tiên, cơ bản nhất", "Nghĩa mới nhất", "Nghĩa ít dùng nhất", "Nghĩa sai"], correctAnswer: "Nghĩa xuất hiện đầu tiên, cơ bản nhất", explanation: "Nghĩa gốc là nghĩa cơ bản, xuất hiện đầu tiên của từ." },
    ],
  },
  {
    subjectId: "tieng-viet",
    grade: 5,
    order: 3,
    questions: [
      { type: "multiple_choice", content: "Từ nào sau đây là đại từ nhân xưng?", options: ["Tôi, bạn, họ", "Đẹp, xấu, cao", "Chạy, nhảy, hát", "Bàn, ghế, sách"], correctAnswer: "Tôi, bạn, họ", explanation: "Đây đều là các đại từ nhân xưng." },
      { type: "multiple_choice", content: "Đại từ 'nó' thường dùng để thay thế cho gì?", options: ["Người, vật đã được nhắc đến", "Chỉ con người", "Chỉ đồ vật", "Không thay thế cho gì"], correctAnswer: "Người, vật đã được nhắc đến", explanation: "'Nó' có thể thay thế cho người hoặc vật đã nhắc đến trước đó." },
      { type: "multiple_choice", content: "Câu 'Mẹ mua cho em một cuốn sách. Em rất thích nó.' từ 'nó' thay thế cho từ nào?", options: ["Mẹ", "Em", "Cuốn sách", "Thích"], correctAnswer: "Cuốn sách", explanation: "'Nó' thay thế cho 'cuốn sách' để tránh lặp từ." },
      { type: "multiple_choice", content: "Đại từ 'chúng tôi' và 'chúng ta' khác nhau như thế nào?", options: ["'Chúng ta' bao gồm cả người nghe, 'chúng tôi' thì không", "Không có sự khác biệt", "'Chúng tôi' bao gồm cả người nghe", "Cả hai đều chỉ một người"], correctAnswer: "'Chúng ta' bao gồm cả người nghe, 'chúng tôi' thì không", explanation: "Đây là điểm khác biệt tinh tế giữa hai đại từ này." },
      { type: "multiple_choice", content: "Đại từ nghi vấn nào dùng để hỏi về người?", options: ["Ai", "Gì", "Nào", "Bao nhiêu"], correctAnswer: "Ai", explanation: "'Ai' là đại từ nghi vấn dùng để hỏi về người." },
    ],
  },
  {
    subjectId: "tieng-viet",
    grade: 5,
    order: 4,
    questions: [
      { type: "multiple_choice", content: "Cặp quan hệ từ nào thể hiện sự tương phản?", options: ["Tuy...nhưng", "Vì...nên", "Nếu...thì", "Càng...càng"], correctAnswer: "Tuy...nhưng", explanation: "'Tuy...nhưng' thể hiện sự tương phản giữa hai vế câu." },
      { type: "multiple_choice", content: "Câu 'Vì chăm học nên Lan đạt điểm cao.' dùng cặp quan hệ từ nào?", options: ["Vì...nên", "Tuy...nhưng", "Nếu...thì", "Không những...mà còn"], correctAnswer: "Vì...nên", explanation: "'Vì...nên' thể hiện quan hệ nguyên nhân - kết quả." },
      { type: "multiple_choice", content: "Quan hệ từ 'và' thường dùng để làm gì?", options: ["Nối hai từ ngữ hoặc vế câu có quan hệ ngang hàng", "Chỉ hoạt động", "Chỉ đặc điểm", "Thể hiện câu hỏi"], correctAnswer: "Nối hai từ ngữ hoặc vế câu có quan hệ ngang hàng", explanation: "'Và' dùng để nối các thành phần ngang hàng nhau." },
      { type: "multiple_choice", content: "Cặp quan hệ từ nào thể hiện mức độ tăng dần?", options: ["Càng...càng", "Vì...nên", "Tuy...nhưng", "Nếu...thì"], correctAnswer: "Càng...càng", explanation: "'Càng...càng' thể hiện mức độ tăng dần, ví dụ 'Càng học càng giỏi.'" },
      { type: "multiple_choice", content: "Quan hệ từ giúp câu văn trở nên như thế nào?", options: ["Rõ ràng, mạch lạc hơn về mối quan hệ ý nghĩa", "Khó hiểu hơn", "Ngắn gọn hơn", "Không có tác dụng gì"], correctAnswer: "Rõ ràng, mạch lạc hơn về mối quan hệ ý nghĩa", explanation: "Quan hệ từ giúp thể hiện rõ mối quan hệ giữa các ý trong câu." },
    ],
  },
  {
    subjectId: "tieng-viet",
    grade: 5,
    order: 5,
    questions: [
      { type: "multiple_choice", content: "Từ nào có thể thay thế cho một danh từ đã nhắc đến trước đó?", options: ["Đại từ", "Tính từ", "Động từ", "Số từ"], correctAnswer: "Đại từ", explanation: "Đại từ thường được dùng để thay thế, giúp liên kết câu." },
      { type: "multiple_choice", content: "Câu 'Hôm nay trời đẹp. Vì vậy, cả nhà đi picnic.' liên kết bằng cách nào?", options: ["Dùng từ nối 'vì vậy'", "Lặp từ", "Thay thế từ", "Không liên kết"], correctAnswer: "Dùng từ nối 'vì vậy'", explanation: "'Vì vậy' là từ nối thể hiện quan hệ nguyên nhân - kết quả giữa hai câu." },
      { type: "multiple_choice", content: "Liên kết câu có vai trò gì trong một đoạn văn?", options: ["Giúp các câu gắn kết chặt chẽ với nhau về nội dung", "Làm đoạn văn dài hơn", "Làm đoạn văn khó đọc", "Không có vai trò gì"], correctAnswer: "Giúp các câu gắn kết chặt chẽ với nhau về nội dung", explanation: "Liên kết câu giúp đoạn văn có nội dung thống nhất, chặt chẽ." },
      { type: "multiple_choice", content: "Cách lặp từ ngữ để liên kết câu có nhược điểm gì nếu lạm dụng?", options: ["Làm đoạn văn nhàm chán, đơn điệu", "Làm câu văn hay hơn", "Không có nhược điểm gì", "Làm câu văn ngắn hơn"], correctAnswer: "Làm đoạn văn nhàm chán, đơn điệu", explanation: "Lặp từ quá nhiều có thể làm đoạn văn trở nên đơn điệu." },
      { type: "multiple_choice", content: "Từ nối nào thể hiện sự bổ sung ý?", options: ["Ngoài ra, hơn nữa", "Tuy nhiên", "Vì vậy", "Nhưng"], correctAnswer: "Ngoài ra, hơn nữa", explanation: "'Ngoài ra', 'hơn nữa' dùng để bổ sung thêm ý cho câu trước." },
    ],
  },
  {
    subjectId: "tieng-viet",
    grade: 5,
    order: 6,
    questions: [
      { type: "multiple_choice", content: "Từ nào có nghĩa gần với 'hữu nghị'?", options: ["Thân thiết", "Xa lạ", "Thù ghét", "Ganh đua"], correctAnswer: "Thân thiết", explanation: "'Thân thiết' có nghĩa gần với 'hữu nghị'." },
      { type: "multiple_choice", content: "Việc hợp tác giữa các quốc gia giúp mang lại điều gì?", options: ["Hòa bình và phát triển", "Chiến tranh", "Xung đột", "Chia rẽ"], correctAnswer: "Hòa bình và phát triển", explanation: "Hợp tác giữa các quốc gia thường mang lại hòa bình và phát triển." },
      { type: "multiple_choice", content: "Từ nào KHÔNG thuộc chủ đề hòa bình?", options: ["Xung đột", "Yên ổn", "Hợp tác", "Đoàn kết"], correctAnswer: "Xung đột", explanation: "'Xung đột' trái ngược với tinh thần hòa bình." },
      { type: "multiple_choice", content: "'Đoàn kết' và 'chia rẽ' là hai từ có quan hệ gì?", options: ["Trái nghĩa", "Đồng nghĩa", "Không liên quan", "Từ nhiều nghĩa"], correctAnswer: "Trái nghĩa", explanation: "'Đoàn kết' và 'chia rẽ' có nghĩa trái ngược nhau." },
      { type: "multiple_choice", content: "Ngày Quốc tế Hòa bình nhắc nhở con người điều gì?", options: ["Trân trọng hòa bình, tránh xung đột", "Nên gây chiến tranh", "Không cần đoàn kết", "Chỉ nên nghĩ đến bản thân"], correctAnswer: "Trân trọng hòa bình, tránh xung đột", explanation: "Ngày này nhắc nhở mọi người trân trọng và gìn giữ hòa bình." },
    ],
  },
  {
    subjectId: "tieng-viet",
    grade: 5,
    order: 7,
    questions: [
      { type: "multiple_choice", content: "Khi tả một người bạn, con nên bắt đầu bằng điều gì?", options: ["Giới thiệu chung về người đó", "Chỉ nói tên và kết thúc", "Kể một câu chuyện không liên quan", "Không cần giới thiệu gì"], correctAnswer: "Giới thiệu chung về người đó", explanation: "Nên giới thiệu chung trước khi đi vào miêu tả chi tiết." },
      { type: "multiple_choice", content: "Câu văn nào miêu tả sinh động hơn?", options: ["Bầu trời trong xanh, cao vời vợi như một tấm lụa khổng lồ.", "Bầu trời có màu xanh.", "Trời xanh.", "Bầu trời màu xanh, không có mây."], correctAnswer: "Bầu trời trong xanh, cao vời vợi như một tấm lụa khổng lồ.", explanation: "Câu này dùng hình ảnh so sánh sinh động hơn." },
      { type: "multiple_choice", content: "Khi miêu tả cảnh, con có thể dùng giác quan nào để quan sát?", options: ["Thị giác, thính giác, khứu giác", "Chỉ thị giác", "Chỉ thính giác", "Không cần giác quan nào"], correctAnswer: "Thị giác, thính giác, khứu giác", explanation: "Có thể dùng nhiều giác quan để miêu tả cảnh vật sinh động hơn." },
      { type: "multiple_choice", content: "Phần kết bài văn tả cảnh thường nêu điều gì?", options: ["Cảm nghĩ của người viết về cảnh đó", "Chỉ liệt kê lại các chi tiết", "Không cần viết gì thêm", "Chỉ nêu tên cảnh"], correctAnswer: "Cảm nghĩ của người viết về cảnh đó", explanation: "Phần kết thường nêu cảm nghĩ, tình cảm của người viết." },
      { type: "multiple_choice", content: "Câu văn tả người cần tránh điều gì để không bị nhàm chán?", options: ["Chỉ liệt kê đặc điểm mà không có cảm xúc", "Miêu tả ngoại hình", "Miêu tả tính cách", "Sử dụng từ ngữ gợi hình"], correctAnswer: "Chỉ liệt kê đặc điểm mà không có cảm xúc", explanation: "Cần tránh chỉ liệt kê khô khan mà nên có cảm xúc, hình ảnh sinh động." },
    ],
  },
  {
    subjectId: "tieng-viet",
    grade: 5,
    order: 8,
    questions: [
      { type: "multiple_choice", content: "Gia đình Lan thường làm gì để tưởng nhớ công lao của ông?", options: ["Nghe ông kể chuyện chiến đấu mỗi dịp Tết", "Không làm gì cả", "Đi du lịch xa", "Quên đi quá khứ"], correctAnswer: "Nghe ông kể chuyện chiến đấu mỗi dịp Tết", explanation: "Bài đọc kể cả nhà quây quần nghe ông kể chuyện mỗi dịp Tết." },
      { type: "multiple_choice", content: "Câu chuyện của ông giúp Lan hiểu thêm điều gì?", options: ["Giá trị của hòa bình và sự hy sinh của thế hệ trước", "Cách nấu ăn ngon", "Cách chơi thể thao", "Cách học ngoại ngữ"], correctAnswer: "Giá trị của hòa bình và sự hy sinh của thế hệ trước", explanation: "Câu chuyện giúp Lan hiểu và trân trọng sự hy sinh của thế hệ đi trước." },
      { type: "multiple_choice", content: "'Cựu chiến binh' nghĩa là gì?", options: ["Người từng tham gia chiến đấu, nay đã giải ngũ", "Người mới nhập ngũ", "Người chưa từng đi lính", "Người làm nghề giáo viên"], correctAnswer: "Người từng tham gia chiến đấu, nay đã giải ngũ", explanation: "'Cựu chiến binh' là người từng chiến đấu, nay không còn phục vụ trong quân đội." },
      { type: "multiple_choice", content: "Lòng biết ơn thể hiện qua hành động nào của Lan?", options: ["Quyết tâm học giỏi để xứng đáng với sự hy sinh của ông cha", "Không quan tâm đến chuyện của ông", "Chỉ thích nghe kể chuyện cho vui", "Muốn trở thành chiến binh ngay"], correctAnswer: "Quyết tâm học giỏi để xứng đáng với sự hy sinh của ông cha", explanation: "Đây là hành động cụ thể thể hiện lòng biết ơn của Lan." },
      { type: "multiple_choice", content: "Bài đọc muốn giáo dục học sinh điều gì?", options: ["Biết ơn và trân trọng những người đã hy sinh vì đất nước", "Không cần quan tâm đến lịch sử", "Chỉ nên nghĩ về tương lai", "Không cần biết ơn ai"], correctAnswer: "Biết ơn và trân trọng những người đã hy sinh vì đất nước", explanation: "Bài đọc giáo dục lòng biết ơn đối với thế hệ đi trước." },
    ],
  },

  // ===== Tiếng Anh — Lớp 5 =====
  {
    subjectId: "tieng-anh",
    grade: 5,
    order: 1,
    questions: [
      { type: "multiple_choice", content: "'She is watching TV.' nghĩa là gì?", options: ["Cô ấy đang xem tivi", "Cô ấy đã xem tivi", "Cô ấy thích xem tivi", "Cô ấy không xem tivi"], correctAnswer: "Cô ấy đang xem tivi", explanation: "'Is watching' là thì hiện tại tiếp diễn, nghĩa là đang xem." },
      { type: "multiple_choice", content: "'What is he doing?' câu trả lời phù hợp là gì?", options: ["He is playing football.", "He plays football every day.", "He likes football.", "He played football."], correctAnswer: "He is playing football.", explanation: "Câu hỏi 'What is he doing?' cần trả lời bằng thì hiện tại tiếp diễn." },
      { type: "multiple_choice", content: "Động từ 'run' khi thêm -ing viết như thế nào?", options: ["Runing", "Running", "Runeing", "Runnning"], correctAnswer: "Running", explanation: "'Run' nhân đôi phụ âm cuối trước khi thêm -ing: 'running'." },
      { type: "multiple_choice", content: "'They are singing a song.' nghĩa là gì?", options: ["Họ đang hát một bài hát", "Họ đã hát một bài hát", "Họ thích hát", "Họ không hát"], correctAnswer: "Họ đang hát một bài hát", explanation: "'Are singing' nghĩa là đang hát." },
      { type: "multiple_choice", content: "Từ 'now' (bây giờ) thường xuất hiện cùng thì nào?", options: ["Thì hiện tại tiếp diễn", "Thì quá khứ", "Thì tương lai", "Không thì nào"], correctAnswer: "Thì hiện tại tiếp diễn", explanation: "'Now' thường đi cùng thì hiện tại tiếp diễn để chỉ hành động đang xảy ra." },
    ],
  },
  {
    subjectId: "tieng-anh",
    grade: 5,
    order: 2,
    questions: [
      { type: "multiple_choice", content: "'The bus is slower than the plane.' nghĩa là gì?", options: ["Xe buýt chậm hơn máy bay", "Xe buýt nhanh hơn máy bay", "Xe buýt bằng máy bay", "Máy bay chậm hơn xe buýt"], correctAnswer: "Xe buýt chậm hơn máy bay", explanation: "'Slower' nghĩa là chậm hơn." },
      { type: "multiple_choice", content: "'Shorter' nghĩa là gì?", options: ["Cao hơn", "Thấp hơn", "Dài hơn", "To hơn"], correctAnswer: "Thấp hơn", explanation: "'Shorter' nghĩa là thấp hơn/ngắn hơn." },
      { type: "multiple_choice", content: "Khi so sánh hai vật, tính từ ngắn thường thêm đuôi gì?", options: ["-er", "-ing", "-ed", "-s"], correctAnswer: "-er", explanation: "Tính từ ngắn thường thêm '-er' khi so sánh hơn." },
      { type: "multiple_choice", content: "'My bag is heavier than yours.' nghĩa là gì?", options: ["Cặp của tôi nặng hơn cặp của bạn", "Cặp của tôi nhẹ hơn cặp của bạn", "Cặp của tôi giống cặp của bạn", "Cặp của bạn nặng hơn"], correctAnswer: "Cặp của tôi nặng hơn cặp của bạn", explanation: "'Heavier' nghĩa là nặng hơn." },
      { type: "multiple_choice", content: "Từ nào nghĩa là 'to hơn'?", options: ["Bigger", "Smaller", "Faster", "Slower"], correctAnswer: "Bigger", explanation: "'Bigger' nghĩa là to hơn, lớn hơn." },
    ],
  },
  {
    subjectId: "tieng-anh",
    grade: 5,
    order: 3,
    questions: [
      { type: "multiple_choice", content: "'I have a toothache.' nghĩa là gì?", options: ["Tôi bị đau răng", "Tôi bị đau đầu", "Tôi bị đau bụng", "Tôi bị sốt"], correctAnswer: "Tôi bị đau răng", explanation: "'Toothache' nghĩa là đau răng." },
      { type: "multiple_choice", content: "'Take medicine' nghĩa là gì?", options: ["Uống thuốc", "Ăn cơm", "Uống nước", "Đi ngủ"], correctAnswer: "Uống thuốc", explanation: "'Take medicine' nghĩa là uống thuốc." },
      { type: "multiple_choice", content: "'Rest' khi bị ốm nghĩa là gì?", options: ["Nghỉ ngơi", "Chạy nhảy", "Học bài", "Chơi thể thao"], correctAnswer: "Nghỉ ngơi", explanation: "'Rest' nghĩa là nghỉ ngơi." },
      { type: "multiple_choice", content: "Câu 'What's wrong with you?' hỏi về điều gì?", options: ["Con đang gặp vấn đề sức khỏe gì", "Con tên là gì", "Con bao nhiêu tuổi", "Con thích ăn gì"], correctAnswer: "Con đang gặp vấn đề sức khỏe gì", explanation: "Câu này hỏi thăm về tình trạng sức khỏe." },
      { type: "multiple_choice", content: "'Healthy' nghĩa là gì?", options: ["Khỏe mạnh", "Ốm yếu", "Mệt mỏi", "Đau đớn"], correctAnswer: "Khỏe mạnh", explanation: "'Healthy' nghĩa là khỏe mạnh." },
    ],
  },
  {
    subjectId: "tieng-anh",
    grade: 5,
    order: 4,
    questions: [
      { type: "multiple_choice", content: "'Reduce, reuse, recycle' là ba việc làm gì để bảo vệ môi trường?", options: ["Giảm thiểu, tái sử dụng, tái chế", "Xả rác, đốt rác, chặt cây", "Lãng phí, ô nhiễm, phá rừng", "Không làm gì cả"], correctAnswer: "Giảm thiểu, tái sử dụng, tái chế", explanation: "Đây là 3 nguyên tắc quan trọng để bảo vệ môi trường." },
      { type: "multiple_choice", content: "'Plant a tree' nghĩa là gì?", options: ["Trồng một cái cây", "Chặt một cái cây", "Tưới nước cho cây", "Nhổ cỏ"], correctAnswer: "Trồng một cái cây", explanation: "'Plant a tree' nghĩa là trồng cây." },
      { type: "multiple_choice", content: "'Global warming' nghĩa là gì?", options: ["Sự nóng lên toàn cầu", "Sự lạnh đi toàn cầu", "Sự ô nhiễm nước", "Sự sạch sẽ"], correctAnswer: "Sự nóng lên toàn cầu", explanation: "'Global warming' nghĩa là hiện tượng nóng lên toàn cầu." },
      { type: "multiple_choice", content: "Việc nào giúp tiết kiệm năng lượng?", options: ["Turn off the lights when not in use", "Leave the TV on all day", "Waste water", "Cut down trees"], correctAnswer: "Turn off the lights when not in use", explanation: "Tắt đèn khi không dùng giúp tiết kiệm năng lượng." },
      { type: "multiple_choice", content: "'Clean energy' nghĩa là gì?", options: ["Năng lượng sạch", "Năng lượng bẩn", "Rác thải", "Khói bụi"], correctAnswer: "Năng lượng sạch", explanation: "'Clean energy' nghĩa là năng lượng sạch, thân thiện môi trường." },
    ],
  },
  {
    subjectId: "tieng-anh",
    grade: 5,
    order: 5,
    questions: [
      { type: "multiple_choice", content: "Vào dịp Tết, người Việt Nam thường làm gì?", options: ["Visit relatives and eat special food", "Go to school as usual", "Stay at home alone", "Go to work"], correctAnswer: "Visit relatives and eat special food", explanation: "Tết là dịp thăm họ hàng và ăn những món ăn đặc biệt." },
      { type: "multiple_choice", content: "'Halloween' là lễ hội có nguồn gốc từ đâu?", options: ["Phương Tây", "Việt Nam", "Trung Quốc", "Nhật Bản"], correctAnswer: "Phương Tây", explanation: "'Halloween' là lễ hội có nguồn gốc từ phương Tây." },
      { type: "multiple_choice", content: "'Decorate' nghĩa là gì?", options: ["Trang trí", "Dọn dẹp", "Nấu ăn", "Mua sắm"], correctAnswer: "Trang trí", explanation: "'Decorate' nghĩa là trang trí." },
      { type: "multiple_choice", content: "Vào Tết Trung thu, trẻ em thường làm gì?", options: ["Rước đèn lồng", "Đi học thêm", "Đi làm việc", "Ở nhà một mình"], correctAnswer: "Rước đèn lồng", explanation: "Rước đèn lồng là hoạt động quen thuộc vào Tết Trung thu." },
      { type: "multiple_choice", content: "'Celebrate' nghĩa là gì?", options: ["Ăn mừng, kỷ niệm", "Buồn bã", "Tức giận", "Sợ hãi"], correctAnswer: "Ăn mừng, kỷ niệm", explanation: "'Celebrate' nghĩa là ăn mừng, tổ chức kỷ niệm." },
    ],
  },
  {
    subjectId: "tieng-anh",
    grade: 5,
    order: 6,
    questions: [
      { type: "multiple_choice", content: "Người đến từ China gọi là gì?", options: ["Chinese", "China", "Chinaese", "Chinesee"], correctAnswer: "Chinese", explanation: "Người đến từ China gọi là 'Chinese'." },
      { type: "multiple_choice", content: "'Where are you from?' hỏi về điều gì?", options: ["Con đến từ đâu", "Con tên là gì", "Con bao nhiêu tuổi", "Con thích gì"], correctAnswer: "Con đến từ đâu", explanation: "Câu này hỏi về quốc gia/nơi xuất thân." },
      { type: "multiple_choice", content: "'I am from Vietnam.' nghĩa là gì?", options: ["Tôi đến từ Việt Nam", "Tôi đến từ Nhật Bản", "Tôi đến từ Anh", "Tôi đến từ Mỹ"], correctAnswer: "Tôi đến từ Việt Nam", explanation: "'I am from Vietnam.' nghĩa là tôi đến từ Việt Nam." },
      { type: "multiple_choice", content: "Người đến từ Korea gọi là gì?", options: ["Korean", "Korea", "Koreaese", "Koreanese"], correctAnswer: "Korean", explanation: "Người đến từ Korea gọi là 'Korean'." },
      { type: "multiple_choice", content: "'Nationality' nghĩa là gì?", options: ["Quốc tịch", "Ngôn ngữ", "Tôn giáo", "Nghề nghiệp"], correctAnswer: "Quốc tịch", explanation: "'Nationality' nghĩa là quốc tịch." },
    ],
  },
  {
    subjectId: "tieng-anh",
    grade: 5,
    order: 7,
    questions: [
      { type: "multiple_choice", content: "'I am going to study English next year.' nghĩa là gì?", options: ["Năm sau tôi định học Tiếng Anh", "Tôi đã học Tiếng Anh năm ngoái", "Tôi không thích Tiếng Anh", "Tôi đang học Tiếng Anh"], correctAnswer: "Năm sau tôi định học Tiếng Anh", explanation: "'Going to' diễn tả dự định trong tương lai." },
      { type: "multiple_choice", content: "'What are your plans for the summer?' hỏi về điều gì?", options: ["Kế hoạch mùa hè", "Kế hoạch mùa đông", "Việc đã làm hôm qua", "Món ăn yêu thích"], correctAnswer: "Kế hoạch mùa hè", explanation: "Câu này hỏi về dự định trong mùa hè." },
      { type: "multiple_choice", content: "'Next week' nghĩa là gì?", options: ["Tuần tới", "Tuần trước", "Hôm nay", "Hôm qua"], correctAnswer: "Tuần tới", explanation: "'Next week' nghĩa là tuần tới, chỉ thời gian trong tương lai." },
      { type: "multiple_choice", content: "Câu nào diễn tả dự định trong tương lai?", options: ["I am going to visit Hanoi.", "I visited Hanoi last year.", "I like Hanoi.", "I live in Hanoi."], correctAnswer: "I am going to visit Hanoi.", explanation: "Câu này dùng cấu trúc 'going to' để nói về dự định." },
      { type: "multiple_choice", content: "'Tomorrow' nghĩa là gì?", options: ["Ngày mai", "Hôm nay", "Hôm qua", "Tuần này"], correctAnswer: "Ngày mai", explanation: "'Tomorrow' nghĩa là ngày mai." },
    ],
  },
  {
    subjectId: "tieng-anh",
    grade: 5,
    order: 8,
    questions: [
      { type: "multiple_choice", content: "'Hill' nghĩa là gì?", options: ["Đồi", "Núi cao", "Sông", "Biển"], correctAnswer: "Đồi", explanation: "'Hill' nghĩa là đồi (thấp hơn núi)." },
      { type: "multiple_choice", content: "'Cave' nghĩa là gì?", options: ["Hang động", "Thác nước", "Sa mạc", "Đại dương"], correctAnswer: "Hang động", explanation: "'Cave' nghĩa là hang động." },
      { type: "multiple_choice", content: "'Lake' nghĩa là gì?", options: ["Hồ", "Sông", "Biển", "Suối"], correctAnswer: "Hồ", explanation: "'Lake' nghĩa là hồ." },
      { type: "multiple_choice", content: "Nơi nào có nhiều cát, ít nước?", options: ["Desert", "Forest", "Ocean", "River"], correctAnswer: "Desert", explanation: "Sa mạc (desert) có nhiều cát và rất ít nước." },
      { type: "multiple_choice", content: "'Island' nghĩa là gì?", options: ["Hòn đảo", "Ngọn núi", "Con sông", "Khu rừng"], correctAnswer: "Hòn đảo", explanation: "'Island' nghĩa là hòn đảo." },
    ],
  },
];
